### ISSUE TITLE
SoL 3: How Do Students Solve Problems?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#101]

**Comment by uiuc-cse** [comment]
-   [The paper](https://github.com/swcarpentry/instructor-training/blob/gh-pages/papers/science-of-learning-2015.pdf)

<blockquote>
Each subject area has some set of facts that, if committed to long-term memory, aids problem-solving by freeing working memory resources and illuminating contexts in which existing knowledge and skills can be applied.  The size and content of this set varies by subject matter.
<br/>
Effective feedback is often essential to acquiring new knowledge and skills.
</blockquote>

The bulk of this topic is addressed by [*3.  Mental Models*](Mental Models).  To a lesser extent, this is addressed as well by [*5.  Mapping Expertise*](https://swcarpentry.github.io/instructor-training/05-expertise.html), by [*6.  Managing Memory*](https://swcarpentry.github.io/instructor-training/06-memory.html) and by [*7.  Lesson Design*](https://swcarpentry.github.io/instructor-training/07-design.html).

**Comment by davis68** [comment]
-   [The paper](https://github.com/swcarpentry/instructor-training/blob/gh-pages/papers/science-of-learning-2015.pdf)

<blockquote>
Each subject area has some set of facts that, if committed to long-term memory, aids problem-solving by freeing working memory resources and illuminating contexts in which existing knowledge and skills can be applied.  The size and content of this set varies by subject matter.
<br/>
Effective feedback is often essential to acquiring new knowledge and skills.
</blockquote>

The bulk of this topic is addressed by [*3.  Mental Models*](Mental Models).  To a lesser extent, this is addressed as well by [*5.  Mapping Expertise*](https://swcarpentry.github.io/instructor-training/05-expertise.html), by [*6.  Managing Memory*](https://swcarpentry.github.io/instructor-training/06-memory.html) and by [*7.  Lesson Design*](https://swcarpentry.github.io/instructor-training/07-design.html).

**Comment by davis68** [comment]
As far as *HLW* goes, student problem-solving largely falls into the chapters:

2.  How students organize knowledge influences how they learn and how they apply what they know.

4.  To develop mastery, students must acquire component skills, practice integrating them, and know when to apply what they have learned.

5.  Goal-directed practice coupled with targeted feedback enhances the quality of students' learning.

7.  To become self-directed learners, students must learn to monitor and adjust their approaches to learning.

**Comment by davis68** [comment]
Some things that I haven't seen addressed in the instructor training (current version):

-   managing multiple channels for optimal learning (I see dual-channel usage deprecated in lesson 6)—looks like the bibliography has a little, but I don't see it in the lesson.  Maybe I'm off in the weeds here, but it seems to me that at least two channels are always complementary—vision and hearing—and a good model of how to *manage* those two channels is key.  (Graphics complementing a spoken explanation, for instance.)
-   calibrating tools and platform usage to the audience (things like Jupyter are often new and strange—a couple of new and strange things are okay, many are overwhelming)
-   when to use the whiteboard and when to use slides—this should be more than a matter of preference and we should have compelling reasons to select one or the other

**Comment by wking** [comment]
On Tue, Mar 08, 2016 at 12:02:10PM -0800, Computational Science & Engineering wrote:
> Each subject area has some set of facts that, if committed to
> long-term memory, aids problem-solving by freeing working memory
> resources and illuminating contexts in which existing knowledge and
> skills can be applied.

This idea is also covered in more detail in the Kirschner, Sweller,
and Clark 2006 paper I mentioned in discuss@ recently [1].  I see the
SoL paper cites them as reference 7 in §1.

[1]: http://lists.software-carpentry.org/pipermail/discuss_lists.software-carpentry.org/2016-March/004034.html
     Subject: Re: [Discuss] Leave students by themselves during hands-on
     Date: Sat, 5 Mar 2016 14:15:38 -0800
     Message-ID: <20160305221538.GA21887@odin.tremily.us>

**Comment by davis68** [comment]
> calibrating tools and platform usage to the audience (things like Jupyter are often new and strange—a couple of new and strange things are okay, many are overwhelming)

So I suppose the optimal rule of thumb is to introduce only one new thing at a time (orthogonality).  How quickly do things drop off after that?  I'd argue it's a power law:  two new things simultaneously is probably about four times or so as hard to deal with, and beyond that you've lost people completely in most cases (certainly in a workshop format with time limitations).

**Comment by gvwilson** [comment]
I don't know of any research to back a power law, but I'd be amazed if 
it wasn't true...  And it's certainly convincing...
