### ISSUE TITLE
Trainee PRs for python-novice-inflammation

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [swcarpentry/instructor-training#110]
Help evaluate and summarize the types of PRs coming against the python novice lesson. The last time I taught I was surprised (overwhelmed) by how much material there was (relative to what one could be expected to cover).

**Comment by JasonJWilliamsNY** [comment]
@gvwilson what is the procedure for this? I see instructor PRs are tagged, but how many should I review and where is there a structure we are following on this?

**Comment by gvwilson** [comment]
Please go through a dozen or so and comment here on any patterns you 
see.  In particular, is there anything we ought to tell them during 
instructor training that we're not saying or they're not hearing?
