### ISSUE TITLE
Add a section on myths

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#114]
reflecting Guzdial's "10 Myths" and http://patitsas.blogspot.ca/2016/01/cs-grades-probably-more-normal-than-you.html from @patitsas.

**Comment by davis68** [comment]
Another resource (when someone has time to read it):  [Urban Myths About Learning](http://www.amazon.com/gp/product/0128015373?keywords=urban%20myths%20in%20teaching&qid=1458067566&ref_=sr_1_1&sr=8-1)

**Comment by gvwilson** [comment]
I just finished "Urban Myths About Learning", and I'll incorporate some points into training, but I was a bit taken aback by how often they quoted John Hattie's work - people in the CS Ed community have been pretty scathing about how fast and loose he plays with stats when doing meta-meta-studies.

**Comment by davis68** [comment]
Unsurprising—it drives me nuts when authors over-rely on someone in particular.

I've not drilled deeply, but as I recall I have encountered evidence that leads me to believe several of the "myths" listed are not in fact myths.  Probably overlapping vintages of academic publishing, but I'll reserve judgment until I get a change to read the book.
