### ISSUE TITLE
Link to Allen and Tanner doesn't render

### ISSUE THREAD

**Issue by arokem** [swcarpentry/instructor-training#118]
In http://swcarpentry.github.io/instructor-training/07-design.html:

<img width="1122" alt="screen shot 2016-03-06 at 2 33 20 pm" src="https://cloud.githubusercontent.com/assets/118582/13557589/7a1bc0ea-e3a8-11e5-88da-649ca1798f08.png">

Maybe because it is embedded in an html table?

**Comment by gvwilson** [comment]
Fixed in 222b08c
