### ISSUE TITLE
Trainee PRs for shell-novice

### ISSUE THREAD

**Issue by weaverbel** [swcarpentry/instructor-training#119]
I am going to work my way through the PRs from instructor training - so far I have liked one new exercise/challenge (https://github.com/swcarpentry/shell-novice/pull/334) as I think it does test understanding of wildcards

**Comment by weaverbel** [comment]
I think it is confusing to ask two questions in a challenge - better to stick to one https://github.com/swcarpentry/shell-novice/pull/343

**Comment by weaverbel** [comment]
I like the fact that people have to demonstrate they can do this - good testing of understanding of what they should have learned earlier with FOR loops https://github.com/swcarpentry/shell-novice/pull/340

**Comment by weaverbel** [comment]
Most of the pull requests so far are short and easy to scan but this one is just huge and seems to have so many differences and I would find that intimidating ! https://github.com/swcarpentry/shell-novice/pull/333

**Comment by weaverbel** [comment]
The two I have liked the best so far are from people I know ! I like this tip on how to debug a script https://github.com/swcarpentry/shell-novice/pull/331 - not too long, and fairly easy to scan quickly.

**Comment by weaverbel** [comment]
Pull requests need to be short and specific - this one has far too many changes in it https://github.com/swcarpentry/shell-novice/pull/326 - and there are typos in what has been changed which adds work for the maintainer.

And this one has a challenge https://github.com/swcarpentry/shell-novice/pull/319/ that seems like a challenge for the sake of it rather than to do anything useful or relevant

**Comment by weaverbel** [comment]
Some PRs are too short ! https://github.com/swcarpentry/shell-novice/pull/285/ seems to be only half an exercise.

**Comment by weaverbel** [comment]
We do have a lot of long challenges - they are not bad, per se, but they take quite a long time to read - probably not ideal for teaching purposes: https://github.com/swcarpentry/shell-novice/pull/287 and https://github.com/swcarpentry/shell-novice/pull/288

**Comment by weaverbel** [comment]
This is good as a tip https://github.com/swcarpentry/shell-novice/pull/290/ as it prompts you with *Are you sure?* before you delete something forever

**Comment by weaverbel** [comment]
This is my favourite so far - it is a little bit long, but it tests knowledge and people would feel satisfied if they got it right. Also I like the add on challenge of trying to do the job with fewer commands which people could do/not do as they felt like it https://github.com/swcarpentry/shell-novice/pull/300

**Comment by weaverbel** [comment]
A case of 'too much information' with this https://github.com/swcarpentry/shell-novice/pull/306 and this https://github.com/swcarpentry/shell-novice/pull/301 - both offer useful information but could be info overload for trainees in the class. In the category of 'good to know' but I would not recommend adding to core lessons.

**Comment by weaverbel** [comment]
In the not bad category - tests understanding/memory of what was taught https://github.com/swcarpentry/shell-novice/pull/312

**Comment by gvwilson** [comment]
Agreed - in this case, we should have asked the trainee to flesh it 
out.  This person was a bit of a special case, though, and has already 
qualified - I'll close the PR.

**Comment by hoytpr** [comment]
Regarding  [swcarpentry/shell-novice#326](https://github.com/swcarpentry/shell-novice/pull/326) it was indeed too long and (as my first PR) naive regarding PR etiquette. The PR was for instructor training, but unfortunately attempted to address issues seen on Windows10 computers where the "home" directory is called "Users". Please close this PR.
