### ISSUE TITLE
Where should trainees make their contributions?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#123]

**Comment by weaverbel** [comment]
I think it would be good to have contributions away from the main lessons as that puts too much pressure on the maintainers. So I would be in favour of a special post-instructor-training area. Then, if any contribution was stellar, it could then be pushed over to the actual lesson repo.

From what I have seen reviewing PRs, people are not very clear on what makes a good pull request. Some are too brief, whereas others are humungous with too many changes within the one PR - which probably means they would be rejected. I think we should provide some guidance on what makes a good PR. 

Also on what makes a good challenge - challenges that prove you can do something complicated are pointless if they don't DO anything useful. People don't learn just to master skills for the sake of it - they learn if something has value for them.

**Comment by wking** [comment]
Cross-linking previous discussion in maintainers@ [1].

[1]: http://lists.software-carpentry.org/pipermail/maintainers_lists.software-carpentry.org/2016-January/000130.html
     Subject: [Maintainers] Q: separate file for exercises + allowing trainees to submit diagrams
     Date: Fri, 29 Jan 2016 05:30:09 -0500
     Message-ID: <56AB3F31.2080807@software-carpentry.org>

**Comment by gvwilson** [comment]
My hesitation about a segregated repository for instructor training 
submissions is that the trainees don't get to meet people in the larger 
community and vice versa.  I agree that we need much better guidance on 
what should go in a challenge - I keep telling people to look at the 
existing ones for inspiration, but that doesn't seem to be working.

**Comment by weaverbel** [comment]
Let's develop a few examples - a couple of good ones, and we explain why they're good; a couple of bad ones, and we explain why they're bad - that way they don't have to wade through a lot of stuff without any kind of compass. Some of these people may be new to Git and we don't want to scare them off. 

We also need to address the fairly appalling messages most people put on their PRs. From the many I reviewed, most are too generic and lacking in context.

**Comment by gvwilson** [comment]
But aren't the challenges already in the lessons "good examples"?

**Comment by weaverbel** [comment]
I'm not talking about good examples of *challenges* but good examples of *pull requests* - i.e. what makes one easy to read at a glance to quickly decide yea or nay.

**Comment by weaverbel** [comment]
'Cos you open some of the PRs and your heart just sinks ...

**Comment by gvwilson** [comment]
Ah - yes.

**Comment by wking** [comment]
On Thu, Mar 10, 2016 at 03:13:38PM -0800, Belinda Weaver wrote:
> Let's develop a few examples [of pull requests] - a couple of good
> ones, and we explain why they're good; a couple of bad ones, and we
> explain why they're bad…

Can this go into an intermediate Git lesson [1,2]?  Then trainees and
the SWC community at large can both be learning it in a single
location (if they get it from SWC instead of somewhere else).

[1]: https://github.com/swcarpentry/git-novice/issues/184
[2]: https://github.com/swcarpentry/git-novice/issues/225#issuecomment-179330506
