### ISSUE TITLE
Merge lesson discussion with workshop debriefing

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#139]
I propose that we merge the lesson discussion sessions (part 2 of post-class checkout) with the workshop debriefing sessions run by the mentoring subcommittee. Reasons are:

1. Most of the questions that come up in lesson discussion are actually about the Carpentries more generally.
2. Joining the sessions will give trainees a chance to meet more current instructors, and thereby help their transition into the community.
3. We don't have the resources to keep running multiple parallel sets of meetings.

If we do this, whoever is running the meeting will need to report back on which trainees attended and whether they asked good questions (rather than being passive observers). It also seems sensible to schedule these meetings in two regular weekly slots (because of time zones), rather than juggling them to try to match specific individuals' schedules.

Thoughts?

**Comment by ChristinaLK** [comment]
I will be +1 once the description of what we mean by "attended and asked good questions" (and the  method for reporting that information) has been well defined. 

As a note, the pre/post debriefing sessions have a list of questions associated with them right now, so if we can come up with a parallel instance for the instructors-in-training, it would fit well with what the mentoring committee is already doing in terms of discussion/meeting format.

**Comment by weaverbel** [comment]
+1 from me - just out of mentoring committee and it got voted on there with pretty much everyone in favour.

**Comment by gvwilson** [comment]
Where's the list of debriefing session questions?

**Comment by ChristinaLK** [comment]
http://pad.software-carpentry.org/pre-workshop-morning
http://pad.software-carpentry.org/swc-debriefing-morning

**Comment by anelda** [comment]
+1 I haven't participated in the lesson discussion sessions yet, but think it makes sense to demystify teaching a real workshop for new comers and will help to integrate them into the community while at the same time providing other instructors to assist with the mentoring process.
+1 for clarifying  the description of what we mean by "attended and asked good questions" (and the method for reporting that information) as mentioned by @ChristinaLK

**Comment by tracykteal** [comment]
Thanks for this. Would the requirements for certification then be

- attend and participate (for some definition of participate) in a mentoring meeting (the merge of the lesson discussion and pre-workshop) meetings
- for SWC do a PR
- for DC submit an exercise
- for SWC do the 5 minute teaching on a SWC lesson
- for DC do the 5 minute teaching on a DC lesson

For the FastTrack program (http://www.datacarpentry.org/involved-instructor/ & http://www.datacarpentry.org/blog/fasttrack/) I'm requiring that people attend an onboarding meeting to get certification. I go through an overview of DC and a couple of the lessons (Slides here http://www.slideshare.net/tracykteal/data-carpentry-instructoronboarding), and then have time for questions. Attendance has been high, about 95% of people who have submitted the application, and seems to be useful for people. I can imagine these mentoring meetings filling a similar role, where new instructors or people teaching for the first time in a while have a chance to get an overview and ask questions about workshops in general or particular lessons as they prepare for their checkout on a particular lesson.

**Comment by tracykteal** [comment]
On the point of combing pre-workshop/lesson meetings and debriefing meetings:

I see the challenge of running 'mentoring' meetings and 'debriefing' meetings from a time perspective, but wonder if we can keep them separate. Sorry to be late to the conversation on this. I see debriefings as a way to identify where things could be improved. This is good for new instructors to hear, but is often too much information as they're preparing. It's also a great place to ask for PRs or issues and plan to take action on some of the things that have come. For instance https://github.com/swcarpentry/shell-novice/issues/346 came from a debriefing, and the whole DC R dplyr section came from a debriefing with Kara Woo and Naupaka Zimmerman. 

If debriefing meetings were kept separate, I imagine there wouldn't need to be as many of them as the 'mentoring' meetings. We could also gather debriefing comments via etherpad (while of course also encouraging PRs or issues) if people can't attend in real time. Then if there were particular lesson issues, we could point lesson maintainers to those points. 

Within the Mentoring subcommittee then we could have a 'Mentoring' subgroup focused on materials and meetings for "so you're preparing to teach" and a 'Debriefing' subgroup focused on "so you've just taught" processes and meetings. The 5 minute lesson checkouts would be left to the Instructor Trainers.

**Comment by tracykteal** [comment]
+1 on regular scheduling

How many meetings would be needed a month to have 'mentoring meetings' of about 8 or fewer of new instructors and people interested in attending who are teaching upcoming workshops?

I imagine there could be fewer debriefing meetings. Perhaps 4 a month? I would be particularly interested in being involved in these. I already do many informally.

**Comment by gvwilson** [comment]
1. Yup, those would be the requirements.
2. Easy to add an onboarding meeting if you're going to continue the 
fast track program - do you think there's still a backlog there? (We've 
built your "intro to DC" into the schedule for instructor training from 
now on, so I'm hoping everyone from here forward will be familiar with 
DC before they start the three-step program.)

**Comment by raynamharris** [comment]
+ 1 on merging.  @tracykteal We currently offer 4 post-workshop and 4 pre-workshop session every month.  We could stick with having 8 sessions a month, but I bet we could scale back to 4 and still accommodate the community needs, then add more ad hoc if we need to.

**Comment by lexnederbragt** [comment]
Just a thought: how well are the pre-workshop sessions going, and would that be a place to merge the post-class checkout part with? In that case, an instructor-in-training pretends preparing for their first workshop and attends the pre-workshop session in that role, and we require him/her to ask (to-be-described) "good questions"?

**Comment by k8hertweck** [comment]
@lexnederbragt  The pre-workshop sessions seem productive, albeit with only a few folks attending each time, so there appears to be capacity to merge with instructor checkout in some way. Most of the attendees are from newly trained instructors, anyway! This may be a better solution than merging the instructor checkouts with debriefing.

@tracykteal I understand your reservations about merging all these sessions (pre-workshop, debriefing, and new instructor discussion). My experience hosting several sessions of each type recently leads me to believe that it would not only be workable, but productive. Apart from offering additional time slots for folks to attend, new instructors are very interested in hearing from folks who have a recent teaching experience fresh in their mind. Moreover, our experienced instructors are eager to share advice. 

In general, we may be able to avoid burdening hosts of these sessions with decisions about whether new instructors have asked "good questions" by instead developing a streamlined list of questions about preparing for workshops and using them as fodder for discussion. We can still tell if someone's thought about these details if they actually participate in the discussion.

**Comment by gvwilson** [comment]
Please also see the section titled `### Rubric`in the current pull request in the instructor training notes: https://github.com/swcarpentry/instructor-training/pull/155/files#diff-f93309feecc5f30e1e60ad085e650818R490

**Comment by raynamharris** [comment]
Hi @lexnederbragt and @tracykteal.  I just want to second what @k8hertweck said. The debriefing sessions are going really well and that new instructors really like hearing from experienced instructors. 

I think that in particular, new instructors benefit from hearing thing like what topics were covered or not, where students struggles, what feedback students gave on sticks, what hiccups happened during the workshop and how they were dealt with. 

I almost agree with @tracykteal in that this doesn't really give direct mentorship as for how or what to teach, but I think it participation is a nice confidence booster that will help the instructors be better teachers, and it puts the instructors in touch with more people in the community if they have specific questions. Does that make sense?

**Comment by ChristinaLK** [comment]
Mentoring committee has (most likely) decided to merge sessions.  @gvwilson and @tracykteal, I'll ask you to critique our list of discussion questions.  @k8hertweck should have a draft up soon and I'll make sure you see it.

**Comment by karinlag** [comment]
On 01.04.2016 22:32, Greg Wilson wrote:
> Please also see the section titled |### Rubric|in the current pull
> request in the instructor training notes:
> https://github.com/swcarpentry/instructor-training/pull/155/files#diff-f93309feecc5f30e1e60ad085e650818R490

The first time I read the list of questions, I though that they clearly 
exemplified why I preferred separate discussion sessions for non-checked 
out instructors. However, reading through it again, with a bit of 
phrasing change, these are equally applicable to anybody teaching. The 
only things I would add is something along the lines of

   * Are there things in the material that you don't understand or feel 
uncertain about?
   * Have you thought about where in the material students might more 
easily misunderstand things, or get lost?

Karin

**Comment by gvwilson** [comment]
Added - thanks.

**Comment by gvwilson** [comment]
Done.
