### ISSUE TITLE
miscellaneous things to add to instructors.md if not already clear

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/instructor-training#146]
(pulling from #83)

1. More time for video exercises. Also provide them guidance about how much time they should spend on each feedback. So for example: each video 2 minutes and each feedback about 3 min. I think they were also running out of time because we didn't tell them how long to give feedback on one video. Giving them just the grid for feedback is not enough to structure it.

2. More time for the video on Day 2 when they record themselves live coding. Also give them better guidance for preparations that we want them to pick something from the middle of the materials so that they actually spend most time doing live coding than introducing the topic. This should actually be really well demonstrated during the demo (i.e. how to teach stuff taken out of context and make assumptions that for example people already opened their terminals).

3. During the live coding demo, Tracy purposely made some common mistakes - this worked well when collecting feedback (we did one up one down).

**Comment by gvwilson** [comment]
Point 1 addressed in #141.
