### ISSUE TITLE
adding relevance of material to SWC/DC where possible

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/instructor-training#147]
pulled from #83 

"A very high level comment: when talking about the concepts/theory the trainer needs to make very clear and probably a good few references back to how it ties in with SWC/DC. Sure, yeah, this is supposed to be generic part of the training. However, people come in for SWC/DC and they want to know "Why are you teaching us about cognitive overload? Is this used in SWC/DC". This basically boils down to the trainer being very well read in the pedagogical topics we cover and also be an experiences instructor."

**Comment by apawlik** [comment]
Peer instruction: we encourage students to work together at the workshops.
Mental models vs simple facts: we have just enough time at workshops to help build mental models.
Formative assessment: testing throughout the workshop whether the students are building the correct mental models.

**Comment by ErinBecker** [comment]
@ChristinaLK I'm happy to take this on within the next few work cycles.

**Comment by ErinBecker** [comment]
Along these same lines - add language that ties back readings into lesson material to make them more relevant.

**Comment by lexnederbragt** [comment]
What is the status of this? At this week's UC Davis workshop we were realising the same thing: why don't we use formative assessment in instructor training to check understanding?

**Comment by ErinBecker** [comment]
It depends on the Trainer. We have lots of opportunities for formative assessment throughout instructor training, but many of these aren't explicitly noted in the materials. This is something that I'm very interested in making much more explicit in the reorganized materials. 

@ChristinaLK and I are working on cleaning up the materials according to comments folks made on the outline we discussed at our Business meetings. The new versions are in [this fork](https://github.com/ErinBecker/instructor-training-reorg). We're hoping to have things organized and cleaned up before our Issue Bonanza July 13th and 14th, but folks are certainly free to make PRs to the reorganized materials before then!

**Comment by ErinBecker** [comment]
Closing based on progress in https://github.com/ErinBecker/instructor-training-reorg/.
