### ISSUE TITLE
Have people fill in AMY form when registering for training

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#174]
From discussion with @traykteal: have people fill in the AMY information form (including nearest airport) as a condition of enrolling in training, so that we can see who's near a particular location when putting together future workshops.

**Comment by tracykteal** [comment]
+1 this is a good way to let people who have gone through instructor training, but aren't yet certified know about local opportunities to be a helper, and potentially also as motivation for them to complete instructor training.

**Comment by gvwilson** [comment]
Will be implemented as soon as AMY supports it.
