### ISSUE TITLE
Create top 10 list for instructor training

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#180]
Telling people to read the ops guide isn't working (they're showing up at discussion sessions with lots of uninformed questions). What 10 things should we absolutely positively tell them about what we do?

1. A typical SWC workshop has three modules; a typical DC workshop has... (go through schedule).
2. You teach our material, not your own.
3. We organize some workshops, but we welcome/expect people to organize locally.
4. We expect you to teach at least once in your first year in exchange for this training.
5. You can charge people to attend, and we will charge you when we help organize.

**Comment by smcclatchy** [comment]
- Expect a broad range of expertise and experience. Be prepared to adapt your teaching to accommodate beginners or those who struggle.

**Comment by lexnederbragt** [comment]
* One of the key teaching practices used at Software and Data Carpentry workshops is live coding: instructors don’t use slides, but work through the lesson material, typing in the code or instructions, with the workshop participants following along

(literal quote from the instructor training workshop material)

**Comment by karinlag** [comment]
You need to really thoroughly work through the materials before teaching and verify your own understanding, and also try to figure out where people might misunderstand things and get lost - an addendum is that the material might change between each time you teach.

**Comment by weaverbel** [comment]
Everyone has nerves the first time, and live coding is harder than it looks. Why not get in touch with one of the new guides to practise teaching before you step in front of a class? Or use the lesson discussion sessions to get to know the material better before you teach.

**Comment by embray** [comment]
> You teach our material, not your own.

Do you?  I've frequently taught my own, tailored to the individual audience.

**Comment by lexnederbragt** [comment]
Surely you can teach your own material, but for your workshop to be called a 'Software Carpentry workshop', you need to teach SWC materials. I guess the same holds for Data Carpentry.

**Comment by embray** [comment]
I've been involved in plenty of workshops that were "Official Software Carpentry" workshops but where at least some of the lesson material was lacking in some area or another or not tuned precisely enough.  I usually teach my own lesson on testing.

**Comment by ErinBecker** [comment]
It's important to provide frequent/constant opportunities for learners to let you know whether they're following or have questions (i.e. with sticky notes). Need to be **responsive** to learner difficulties.

**Comment by anelda** [comment]
From  #176 collaborate with your co-instructor and helpers to provide the best possible learning experience for the learners. You're a team - you're never alone in this.

**Comment by gvwilson** [comment]
Closed by 1cf60a8
