### ISSUE TITLE
Bring in Structure-Behaviour-Function Theory?

### ISSUE THREAD

**Issue by patitsas** [swcarpentry/instructor-training#185]
When talking about novice vs. expert programmers, maybe also talk about Structure Behaviour Function Theory? (e.g. http://onlinelibrary.wiley.com/doi/10.1207/s15516709cog2801_7/pdf )

There's evidence that novices see programs in terms of structure; intermediates in terms of its behaviour; experts in terms of function.

**Comment by gvwilson** [comment]
See #203.
