### ISSUE TITLE
exercises?

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/instructor-training#19]
- [ ] create some kind of guide/format for how to do the exercises depending on whether teaching online or in person.  Could be notes like "SG" (for do in small groups) or "Ind" for individual, w/ equivalents for online posting structure.  
- [ ] create a dump/linked version of the assignments *as posted* on Piazza (including how to get people into groups, etc.)?   Could be part of guide above?

**Comment by gvwilson** [comment]
Replaced by #29 and #30.
