### ISSUE TITLE
Add link to Gawande's article about coaches

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#190]
http://www.newyorker.com/magazine/2011/10/03/personal-best

**Comment by ChristinaLK** [comment]
I like his stuff.  :)  

Where were you thinking of putting this?  As part of "teaching study" (mentor/coaching is part of improvement, and you never reach some magical place where you don't need feedback)?

**Comment by gvwilson** [comment]
Hadn't gotten as far as figuring out where it should go...

**Comment by ChristinaLK** [comment]
haha, ok.

**Comment by gvwilson** [comment]
Fixed by 608761f
