### ISSUE TITLE
Create checklists for helpers

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#198]
Like @lexnederbragt 's videos on live coding, show people how to (not) help.

**Comment by lexnederbragt** [comment]
This may be a bit more work to make, as I'm not sure a single camera position/shot will do it. I.e., some video editing may be required. Preferably you can see the problem first, confused face appears, then the red sticky goes up, helper arrives, and the conversation starts.

**Comment by apawlik** [comment]
Or the helper doesn't arrive busy with their mobile :-) That said, I agree with Lex that we would need more than one camera and one person to film it. Some editing skills would also be required.

To throw some ideas in:
- helper *visibly* and *purposely* ignoring a sticky (or hand);
- helper advising/helping the learner in a patronizing matter;
- helper not being able to help (this is OK!) but not doing anything to ask other helpers/instructors to help (this is *not* OK);
- helper *purposely* ignoring the communication from the instructor.

**Comment by raynamharris** [comment]
Other ideas
 - takes command of the keyboard
 - talks louder than the instructor

**Comment by karinlag** [comment]
@apawlik, re patronizing: what would you consider to be patronizing somebody? Just want to have things as concrete as possible

Other things:
  * hanging over a student´s shoulder (i.e. invading their personal space in a massive way)
  * helper trying to find a solution to a problem in "rapid mode" (i.e. googling, changing between windows etc) without explaining what they are doing (sometimes that has to happen to get the student´s problem fixed, but if it is within normalish types of problems, they _should_ take the time to explain

**Comment by lexnederbragt** [comment]
Great suggestions, but perhaps not all can be implemented in a short video, though...

**Comment by ErinBecker** [comment]
I suggest rather than a video this could be a written checklist for helpers. This would be much less resource intensive and also easier to update as we think of things to add. I'm happy to take this on within the next few work cycles. Please add any items you'd like to add to checklist here. I'll also post a link to checklist that can be added to when I work on this.

**Comment by maneesha** [comment]
I also want to include some guidance about the relationship between instructor & helper.  I once volunteered to teach coding for another group where the TAs essentially were guided not to interrupt the instructor unless absolutely necessary, if the instructor did something really wrong.  I told my TAs to ignore that point, that I knew they had tons of knowledge & experience, I wanted their support, and so to please chime in as appropriate/as needed.

**Comment by ErinBecker** [comment]
Incorporated into https://github.com/ErinBecker/instructor-training-reorg/issues/86 and closed here.
