### ISSUE TITLE
Checklists for instructor training events

### ISSUE THREAD

**Issue by jduckles** [swcarpentry/instructor-training#20]
I'd like to develop a set of three checklists for instructor trainers to go through in the lead-up to execution of and post-event.

## Scheduling Event
- [ ] - Set a date
- [ ] - Decide if it will be online or in person
- [ ] - If in-person book travel
- [ ] - meet with host to talk through expectations
- [ ] - make sure host has identified attendees and delivered their names
- [ ] - send email to attendees with background reading and homework assignments 

## Running event 
- [ ] - test video conference link

## Post event
- [ ] - Email attendees about final project requirements
- [ ] - Schedule certifications (3-min lesson online)
- [ ] - Make sure AMY records are filled in
- [ ] - Badge instructors in AMY
- [ ] - Follow up with attendees not badged one month after
- [ ] - Follow up with attendees not badged two months after

I'm sure there are more things I'm forgetting, so please add them!

**Comment by wking** [comment]
On Thu, Nov 12, 2015 at 02:05:01PM -0800, Jonah Duckles wrote:
> I'd like to develop a set of three checklists for instructor trainers…

I'm not sure what level of detail you're aiming for, but [1] goes into
more depth (for example, it includes a template for a pre-workshop
email and includes several rounds of email, a code of conduct mention,
etc., etc.  I'm not sure how instructor-training differs from the
usual events, but it might be easier to start with [1] and adapt than
to start over from scratch.

[1]: http://software-carpentry.org/workshops/checklists/lead_instructor.html

**Comment by gvwilson** [comment]
Moved to https://github.com/swcarpentry/site/issues/1189
