### ISSUE TITLE
Question about sentence in Novices and Formative assessment lesson

### ISSUE THREAD

**Issue by anelda** [swcarpentry/instructor-training#200]
Hi all,

In this lesson I find this sentence maybe not so accurate as we branch out to more audiences 

> We can afford to focus on this aspect of learning because most of our learners are physically safe, well fed, well educated, and highly motivated

People are hopefully in this state at least during the workshop hours, but not necessarily beyond. I would like to think the highly motivated part is true across different audiences, but I suspect not the statements about safety and being well fed.

For an instructor who aren't in this state, reading this sentence might make them feel like the workshop is not developed for them?

**Comment by gvwilson** [comment]
+1 - please suggest alternative wording.

**Comment by anelda** [comment]
I think the question might be asked whether we're focusing on cognitivism because our learners are safe, fed, etc or because we believe it is highly relevant for how we view learning and the active participation of our learners' in their own learning? 
I have very limited knowledge of educational psychology but referred to [1] for a clearer explanation of cognitivism.

Maybe we can just say 

> We care deeply about understanding how people learn and helping learners to actively participate in their own learning during workshops and therefore see the cognitivism theory as very relevant.

I'm certain others can improve on this suggestion?

[1] http://edtech2.boisestate.edu/amyherring/artifacts/504_final_synthesis.pdf
