### ISSUE TITLE
Discuss Henderson et al's work on effecting change

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#208]
http://software-carpentry.org/blog/2016/01/change-strategies-in-stem-education.html has a discussion of a paper related to files/papers/henderson-facilitating-stem-teaching-change-2011.pdf, which discusses ways of effecting change in STEM education.  The grid breakdown is particularly interesting - should we fit this in somewhere (e.g., in place of the learning objectives material, which we rarely get to)?

**Comment by ErinBecker** [comment]
My vote would be that writing good learning objectives is more immediately useful to new instructors. More likely that they'll be teaching something someday than leading pedagogical change efforts.

**Comment by ChristinaLK** [comment]
Maybe in `discussion.md`?  This information seems more meta, which is part of the motivation for this training, but not its actual content.

**Comment by gvwilson** [comment]
Closed by ce7567f
