### ISSUE TITLE
Rearrange material on learning objectives, the Carpentries, and teaching practices

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#209]
The last couple of times I've taught instructor training classes, I've skipped over the material on [writing learning objectives][1] because it's dry as dust.  It also seems out of place on day 2, since we're mostly doing general theory on day 1 and "here's how you apply it to the Carpentries" on day 2.  I therefore propose that we shorten it significantly by:

1. Shortening the discussion of Bloom's taxonomy and relegating it to a callout box.

2. Cutting down to one exercise.

3. Moving the material on reverse instructional design to the end of day 1 (which is where I usually discuss it anyway, since it ties together all of the general theory stuff from that day).

This will free up 15 minutes or so, which isn't much on its own, but I would also like to:

4. Reduce the time allocated for discussion of [the Carpentries in general][2], which is currently 75 minutes (!), since we seem to usually have answered many of these questions by the time we get here.  Pushing a little harder, I think we can combine this with [the discussion of teaching practices][3], since the two often seem to blend into each other.

5. Add short summaries of the core SWC and DC lessons, since we get asked for that pretty much every time we teach.  At 2-3 minutes each, with questions, this'll take 45 minutes.

Thoughts?

[1]: http://swcarpentry.github.io/instructor-training/18-objectives/
[2]: http://swcarpentry.github.io/instructor-training/20-carpentries/
[3]: http://swcarpentry.github.io/instructor-training/14-practices/

**Comment by ChristinaLK** [comment]
I agree that talking about learning objectives is pretty dry - but I think having people write them and/or critique weak learning objectives can be REALLY helpful, especially if we tie it back to the SWC lessons.  

I do agree that it makes more sense on day 1 (where it was originally) - I remember making that fit by not doing an exercise for faded examples (the prev. section) and not talking about Bloom's taxonomy in much detail.  

I have no objection to going over the core SWC/DC lessons - it could be a nice way to help tie together the material from Day 1 with what we actually do, as well as introduce people to the material, encourage them about the checkouts.  

Basically +1.

**Comment by davis68** [comment]
+1.  In general it seems like the topics bleed a *lot* into each other, and this tightens things up.

There was also a comment by the woman who dropped in at the Toronto session—Ph.D. student, CS education, I believe, but I don't recall her name directly—that the research on stereotype threat is controversial and somewhat rescinded now.
