### ISSUE TITLE
Drop down for callouts

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/instructor-training#226]
I'm not sure I really like the new drop down thingy for callouts. For example, when visiting http://swcarpentry.github.io/instructor-training/09-performance/ it at first looks like there is nothing there. It turns out there is something to do but you need to press the little triangle first...

**Comment by ErinBecker** [comment]
I agree - I was confused by this at first and thought the callouts were
blank.

On Fri, Jun 10, 2016 at 11:31 AM, Lex Nederbragt <notifications@github.com>
wrote:

> I'm not sure I really like the new drop down thingy for callouts. For
> example, when visiting
> http://swcarpentry.github.io/instructor-training/09-performance/ it at
> first looks like there is nothing there. It turns out there is something to
> do but you need to press the little triangle first...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/swcarpentry/instructor-training/issues/226>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ASSbf49Ogt0O71n3gmYzxn57rCdAdRErks5qKa2fgaJpZM4IzNQ4>
> .
>



-- 
*Erin Becker*, PhD
Data Carpentry, Associate Director
http://www.datacarpentry.org/
Research Associate, MMG Dept., UC Davis

**Comment by gvwilson** [comment]
There should only be drop-downs for exercises (and their solutions), not 
for callouts or other blocks.  The maintainers wanted them for exercises 
to avoid overwhelming learners.

**Comment by lexnederbragt** [comment]
I see, and this seems indeed to be the case. I guess it works, but again, threw me off when I first saw it at http://swcarpentry.github.io/instructor-training/09-performance/.
