### ISSUE TITLE
Do survey at training

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/instructor-training#228]
Take 10 minutes at the end of training sessions in future for learners to complete the post-training survey.

**Comment by raynamharris** [comment]
I added this to the [last episode](https://github.com/swcarpentry/instructor-training/blob/gh-pages/_episodes/21-summarize.md#post-workshop-survey) already. Is that sufficient

**Comment by gvwilson** [comment]
Works for me - thanks.
