### ISSUE TITLE
Remove exercises we aren't using

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/instructor-training#229]
Remove stuff.  In particular, remove exercises we aren't using, trim text.

**Comment by ChristinaLK** [comment]
I didn't get to this this week and am trying to go off the grid this weekend, so will be tackling this first thing Monday morning.

**Comment by ChristinaLK** [comment]
I didn't get to this this week and am trying to go off the grid this weekend, so will be tackling this first thing Monday morning.

**Comment by gvwilson** [comment]
Can this now be
