### ISSUE TITLE
Add intro episode

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/instructor-training#231]
- current intro lesson to be renamed something like "teaching philosophies" and moved to later in the day
- new intro episode will contain: welcome message, overview of training, and a short multiple choice questions

Goals:
- the multiple choice question will assess about prior knowledge of SWC/DC and some other things, which will help guide the instructors
- the overview should help get all the students on the same page, so they know where they are and where they are going for the whole 3 day training session

**Comment by raynamharris** [comment]
Okay, I created my first pass at a welcome episode here: Create welcome episode 00-welcome.md #232.  Feedback on style and content is welcome.

**Comment by gvwilson** [comment]
Closed by #232 - thanks!
