### ISSUE TITLE
Navigation vanishes on smaller screens

### ISSUE THREAD

**Issue by tomliversidge** [swcarpentry/instructor-training#235]
When viewing on a device with a smaller screen such as a mobile phone, the navigation does not show. This is likely the same issue as https://github.com/neverworkintheory/neverworkintheory.github.io/pull/15

**Comment by gvwilson** [comment]
Is there an easy way to test this on a laptop device?

**Comment by tpoisot** [comment]
Chromium (and I think Firefox) have a mode where you can simulate
smaller devices.

From the top of my head, Ctrl-Maj-I (or right-click -> Inspect), then on
the upper left corner is a small icon with a phone/tablet, click that,
and it opens a view where you can pick the device you want to emulate.

t

Greg Wilson (20/06):
> Is there an easy way to test this on a laptop device?
> 
> 
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/swcarpentry/instructor-training/issues/235#issuecomment-227157730

-- 
Timothée Poisot, Ph.D.
Professeur Adjoint / Assistant Prof.
Quantitative and Computational Ecologist
Département de Sciences Biologiques, Université de Montréal
Web:                   http://poisotlab.io/
Twitter:               @PoisotLab
Schedule a meeting:    http://tpoisot.ycb.me

**Comment by tomliversidge** [comment]
Sure, just resize the browser window

**Comment by tomliversidge** [comment]
Yeah there are add-ons to chrome and Firefox that let you simulate mobile devices

**Comment by tomliversidge** [comment]
https://developers.google.com/web/tools/chrome-devtools/iterate/device-mode should do the job in chrome, but the easiest way to get a quick feel for this sort of thing is to resize the browser window and see what bootstrap does - depending on how it has been written, there might be some logic that changes things once you go below a certain number of horizontal pixels.

**Comment by tomliversidge** [comment]
I should have time tomorrow to look at this if you want?

**Comment by gvwilson** [comment]
Yes please and thank you.
Greg
