### ISSUE TITLE
_extras/checkout.md Conflicting instructions

### ISSUE THREAD

**Issue by cgeroux** [swcarpentry/instructor-training#237]
In "Part1: Submit a Small Change to One of Our Lessons", the paragraph:

> Pick one of the lessons from the list given later in this section and submit a small change. You must submit a change to a Software Carpentry lesson to qualify as a Software Carpentry instructor, and a change to a Data Carpentry lesson to qualify as a Data Carpentry instructor. Instructors seeking dual certification should submit two changes (one to each Carpentry) to ensure they are familiar with the process and the materials.

indicates that two changes should be submitted, one for each carpentry, while item number 5:

> You only have to submit one change to move on to the next step, not one per Carpentry.

Indicates you only need one. Which is the case? Perhaps some clarification could help here.

**Comment by cgeroux** [comment]
Another conflicting statement (or at least one requiring some clarification) with the previously mentioned paragraph in Part 1 is point number 7:

> If you are writing an exercise, we strongly prefer contributions to the Data Carpentry lessons right now (since that material is much younger) or to our fledgling “Python for complete novices” lesson.

According the paragraph mentioned initially there is no choice between contributed to DC or SWC as which you choose is dependent on which instructor training you wish to complete.

**Comment by gvwilson** [comment]
Good catch, Chris - we'll get a patch in as soon as we can.

- Greg

p.s. if someone can invent a way to run regression tests on documentation...

**Comment by ErinBecker** [comment]
@gvwilson I'd like to add to this issue a question I got in email which is: 

Are instructors trying to certify for both Carpentries required to teach two demos and take part in two discussion sessions?

This would make sense if the point of the demos is to ensure that they are familiar with the material (specific to each Carpentry), and also as the discussion session instructions tell trainees to prep by reading through a lesson they want to teach and be prepared to discuss it. 

>"During the session, you are expected to ask questions about issues you noticed while reading your chosen lesson, and about our operations in general. If the discussion leader feels that you have adequately prepared"

Related notes:
a) We don't currently actually quiz trainees on their chosen lesson during a discussion, but just ask them if they have any questions. This language should probably be changed to reflect reality.
b) The checkout says that discussions are conducted via Google Hangouts. This is incorrect. They are all on BlueJeans now.

**Comment by ErinBecker** [comment]
Another potential area of confusion:

> We encourage trainees to submit their changes through GitHub, but will accept submissions for #1 and #2 via email from those who are more comfortable working out of public view.  

vs. 

> If you want to teach Software Carpentry, you must submit the change as a pull request on GitHub. If you want to teach Data Carpentry, you may submit the change either as a pull request or by filing an issue in GitHub that describes your proposed change.  

Sentence one doesn't distinguish between trainee's trying to qualify for SWC or DC. Sentence two does but appears not to allow submission via email as in sentence one.
