### ISSUE TITLE
_episodes/04-performance.md

### ISSUE THREAD

**Issue by davis68** [swcarpentry/instructor-training#238]
> ## The Two-Dimensional You
>
> If you were a cartoon character teacher, who would you be?  What does that say about your
> teaching style?

I don't really understand this exercise.  What are example answers here?  Are we looking for "cartoon character teachers" like [Ludwig von Drake](https://www.youtube.com/watch?v=q566vmQhFHg) or ["cartoon characters [as] teachers"](https://www.youtube.com/watch?v=iIprJoPTJoI)?  (It sounds fun but I don't know how it plays out in practice.  It could make an excellent group icebreaker if moved earlier in the sequence and used in small group discussions.)

**Comment by ChristinaLK** [comment]
This is a bad translation by me of something @gvwilson said at the training I attended at Harvard...something about how when you teach a) you see a "mickey mouse" version of yourself (higher/faster voice b/c of nerves) and b) you also have a teaching "persona" where you aren't really yourself when you teach, but more of the "teacher character" version of yourself.  Maybe a better question would be: "what kind of teaching character are you?" 

Options: turn that into a proper discussion question with context, put these ideas in the text of the lesson, or drop it completely.  I don't have a strong opinion any way, but agree that it probably doesn't serve a purpose the way it is now...

**Comment by ChristinaLK** [comment]
For now, I've dropped the discussion question from the lesson.
