### ISSUE TITLE
A quote I'd like to work into the lessons

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#239]
https://twitter.com/TheWoodenslurpy/status/654850210921754624

**Comment by ErinBecker** [comment]
I'm visibly grimacing right now. Practice is **not** doing the same thing over and over again. Practice is doing similar, but subtly different things, each time, getting feedback (either external or intrinsic (e.g. did the ball go further)), and then changing your behavior in response to that feedback to get cumulatively better. Doing the same thing over and over again is much more likely to solidify bad habits than perfect performance. So, yeah, it's a catchy quote, but . . .

**Comment by tpoisot** [comment]
As a classical musician... I agree.

Greg Wilson (20/06):
> https://twitter.com/TheWoodenslurpy/status/654850210921754624
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/swcarpentry/instructor-training/issues/239

-- 
Timothée Poisot, Ph.D.
Professeur Adjoint / Assistant Prof.
Quantitative and Computational Ecologist
Département de Sciences Biologiques, Université de Montréal
Web:                   http://poisotlab.io/
Twitter:               @PoisotLab
Schedule a meeting:    http://tpoisot.ycb.me

**Comment by apawlik** [comment]
Reflective practice. We already talk about this one, no?

**Comment by alistairwalsh** [comment]
Practice: A feedback loop where different actions are tried to learn their effect on a desired outcome.
Repetitive behaviour: doing the same thing over and over. i.e. Habit, reflexive behaviour. Something that has gone beyond conscious thought and been transfered to automatic response.
Insanity: Doing the same thing over and over with no reflection, feedback or modification and expecting a different result.
On 22 Jun 2016 9:22 a.m., Aleksandra Pawlik <notifications@github.com> wrote:Reflective practice. We already talk about this one, no?
