### ISSUE TITLE
Search box doesn't work as expected

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/instructor-training#249]
(maybe this is the wrong place to report this but I can't find a getter one).

I ran a simple search using the search box at the top right, and the result was strange.

![image](https://cloud.githubusercontent.com/assets/1122351/16450570/085172ce-3dfe-11e6-95b4-f2261a457a62.png)

The URL that was build was

`https://www.google.no/search?q=carpentry+site:/instructor-training&gws_rd=cr&ei=aK9zV7-AFcTosQGKoq6gCA``

I tried Chrome, Chrome in incognito mode, and Firefox (all on the Mac), same result.

**Comment by gvwilson** [comment]
Yup, that's a bug - I'll dig into it next week.
Thanks,
Greg

**Comment by raynamharris** [comment]
@lexnederbragt @gvwilson I also used the search yesterday but it worked just fine for me. I searched for "jupyter notebook" and this was the redirect link that it opened "jupyter notebook site:http://software-carpentry.org/"

Also, your search query directs to "instructor-training site:http://software-carpentry.org/" for me. 

How come I don't have the same problem?

**Comment by gvwilson** [comment]
@lexnederbragt still seeing failures?

**Comment by lexnederbragt** [comment]
Yep...

**Comment by lexnederbragt** [comment]
Seems fixed now.

**Comment by lexnederbragt** [comment]
The problem has reappeared for me. The search becomes:

>datacarpentry site:.

(url https://www.google.no/search?q=datacarpentry+site:.&gws_rd=cr&ei=BivhV6KELsiqsgGK8bNw)

**Comment by gvwilson** [comment]
1. What's the URL of the page you're on when you do the search?
2. What's the search term?
3. What does the search display?

Thx,
G

**Comment by lexnederbragt** [comment]
1. https://swcarpentry.github.io/instructor-training/
2. datacarpentry
3. see screenshot

![image](https://cloud.githubusercontent.com/assets/1122351/18673056/aa7d9932-7f4a-11e6-8bb2-41f989de5603.png)
