### ISSUE TITLE
Add table of Data Carpentry lessons to 15-carpentries.md

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#264]
Similar to the one for SWC lessons.

**Comment by lexnederbragt** [comment]
If you look at http://www.datacarpentry.org/lessons/, there is a table for each set of lessons. So for this page, there would either have to be a similar set of tables, or one very large one...

**Comment by gvwilson** [comment]
Your call...


On 2016-07-11 10:27 AM, Lex Nederbragt wrote:
>
> If you look at http://www.datacarpentry.org/lessons/, there is a table 
> for each set of lessons. So for this page, there would either have to 
> be a similar set of tables, or one very large one...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/swcarpentry/instructor-training/issues/264#issuecomment-231750810>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AA3ozrOMnrKUVUssw4Qo10F4YTWWKJ4-ks5qUlLjgaJpZM4JH8Fh>.
>

-- 
Dr Greg Wilson
Director of Instructor Training
Software Carpentry Foundation

**Comment by lexnederbragt** [comment]
OK, I'll give this a go but it will have to wait till August.

**Comment by lexnederbragt** [comment]
Waiting for merge of #256 before I tackle this one...

**Comment by lexnederbragt** [comment]
I started, but than ran into issues with the Genomics lesson, see https://github.com/datacarpentry/datacarpentry.github.io/issues/140. Putting this on hold for a bit...

**Comment by ErinBecker** [comment]
Suggestion here: https://github.com/swcarpentry/instructor-training/issues/261
