### ISSUE TITLE
Dead link on 15-carpentries

### ISSUE THREAD

**Issue by bmcfee** [swcarpentry/instructor-training#265]
The `overnight homework` link in [this paragraph](https://github.com/swcarpentry/instructor-training/blob/gh-pages/_episodes/15-carpentries.md#preparation-and-discussion) points to a dead link [11-summarize](http://swcarpentry.github.io/instructor-training/11-summarize/).

(I'm reading ahead and trying to find a link for the episodes that @gvwilson mentioned we should look at for homework.)

**Comment by gvwilson** [comment]
Closed by 84eb714 - correct link is http://swcarpentry.github.io/instructor-training/12-summarize/
