### ISSUE TITLE
Somewhere around expert blindspot (or elsewhere), should we mention "empathy"?

### ISSUE THREAD

**Issue by arokem** [swcarpentry/instructor-training#266]
In the human-centered design sense: 

https://dschool.stanford.edu/sandbox/groups/designresources/wiki/36873/attachments/74b3d/ModeGuideBOOTCAMP2010L.pdf?sessionID=68deabe9f22d5b79bde83798d28a09327886ea4b

**Comment by gvwilson** [comment]
What kind of mention do you have in mind?

**Comment by ErinBecker** [comment]
@arokem Were you still interested in incorporating this? 

Please let me know what you'd like to do with this issue. Due to a lack of activity, this issue will be closed on 3/14/17 if no comment by then.

**Comment by ChristinaLK** [comment]
link is dead + no comments - closing this.
