### ISSUE TITLE
The "passive dismissive adjective" isn't an adjective (in this context)

### ISSUE THREAD

**Issue by bobtodd** [swcarpentry/instructor-training#271]
In lesson 8 on Memory we have the passage

> Experts often betray their blind spot by using the word "just" in explanations, as in, "Oh, it's easy, you just fire up a new virtual machine and then you just install these four patches to Ubuntu and then you just re-write your entire program in a pure functional style --- no problem." As we discuss later, the J word (also sometimes called the passive dismissive adjective) is banned in our workshops, primarily because using it gives learners the very clear signal that the instructor thinks their problem is trivial and that they therefore must be stupid.

In this context the word _just_ isn't being used as an adjective, but rather as an adverb:
1. _just_ = _righteous, honest_: adjective;
2. _just_ = _only, simply_: adverb.

Here _just_ is being used as equivalent to _simply_, so it should be the "passive dismissive adverb".

**Comment by ErinBecker** [comment]
Closed with https://github.com/swcarpentry/instructor-training/commit/ce11510167c1508333e18ca9e6beeba6ef5bc652
