### ISSUE TITLE
Example of the "expert blind spot" effect illustrates expert knowledge but not the blind spot

### ISSUE THREAD

**Issue by dstndstn** [swcarpentry/instructor-training#273]
As I understand it, the "expert blind spot" is more about recognizing and communicating knowledge that the expert has internalized and is implicit in their thinking.  Adjust the example to be about communicating knowledge rather than having or using knowledge.

**Comment by ErinBecker** [comment]
Addressed with https://github.com/swcarpentry/instructor-training/pull/274. Thanks @dstndstn
