### ISSUE TITLE
This list reads strangely, like it was meant to be a comment to the writer?

### ISSUE THREAD

**Issue by dstndstn** [swcarpentry/instructor-training#278]
Here,

https://github.com/swcarpentry/instructor-training/blame/gh-pages/_episodes/15-carpentries.md#L364

the list starting "Here are some examples of ways that people have contributed to the community:"
reads rather strangely, as though it is commentary rather than meant to be the actual content.

**Comment by ChristinaLK** [comment]
That is exactly the case - it needs to be filled in with examples.

**Comment by ChristinaLK** [comment]
I think this has been addressed via a later PR.
