### ISSUE TITLE
Where to discuss code of conduct?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#28]
Code of conduct needs to be discussed somewhere - best place?

**Comment by embray** [comment]
+1 for mailing list.

**Comment by gvwilson** [comment]
Sorry, I meant "where in instructor training should it be discussed"?

**Comment by embray** [comment]
Ohh d'oh.  That I don't know.  I need to get back into helping with this material :)

**Comment by karinlag** [comment]
I would say that it should be mentioned first in workshop operations, as in that all instructors should show that first after they have presented SWC, and then at the end of the discussion of workshop operations, as a way of dealing with difficult people, unwanted incidents ++.

**Comment by gvwilson** [comment]
Done - closed by 288ec3c.
