### ISSUE TITLE
confusing wording about checkout time limits

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#280]
"We would like to get everyone through this process within two months of training. Anyone who has not completed within 90 days should contact us to discuss reasons and options" - two months vs. 90 days.

**Comment by ErinBecker** [comment]
@gvwilson Can you point out where this language is coming from?

**Comment by ErinBecker** [comment]
Based on interactions with trainees it appears that the deadline of 90 days "or ask for an extension" is being well communicated. At this point, extensions are being granted most of the time that trainees ask - but it's also true that trainees who are conscientious enough to ask are also completing during their extension. I've only had one instance where I've had to tell someone they weren't able to complete checkout (they had taken training three years ago and never done any follow-up steps). So I'm inclined to close this for now as a non-issue.
