### ISSUE TITLE
Use 'Small Teaching' as a text?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#281]
https://www.amazon.com/Small-Teaching-Everyday-Lessons-Learning/dp/1118944496/ is a good short book on small-scale teaching practices grounded in evidence - use it as a text for instructor training?

**Comment by ErinBecker** [comment]
@gvwilson This and similar issues may best be served by adding a list of supplementary readings for trainees who are interested in learning more about pedagogy and educational research, rather than re-designing the whole curriculum. :-)

Please let me know if you'd like to start a list of readings.
