### ISSUE TITLE
values of SWC/DC

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/instructor-training#284]
Based on the trainers discussion, I wonder if adding a module on the "values" of SWC/DC (maybe in the "software carpentry practices" episodes) would be useful. There's some material there already, but maybe explicitly saying "this is the sort of behavior we expect from our instructors", possibly around the Code of Conduct or Software Carpentry practices.

Challenge to convey culture without being cultish, not finger-wagging at responsible adults, etc. etc.

**Comment by karinlag** [comment]
On 10.08.2016 16:55, Christina Koch wrote:
> Based on the trainers discussion, I wonder if adding a module on the
> "values" of SWC/DC (maybe in the "software carpentry practices"
> episodes) would be useful. There's some material there already, but
> maybe explicitly saying "this is the sort of behavior we expect from our
> instructors", possibly around the Code of Conduct or Software Carpentry
> practices.
>
> Challenge to convey culture without being cultish, not finger-wagging at
> responsible adults, etc. etc.

+1 to this. Can be tricky to get right, but important nevertheless. The 
more diverse people we start drawing in, the more important this gets.

Karin

**Comment by ChristinaLK** [comment]
Closed, discussion re-started in #319
