### ISSUE TITLE
Separate "to trainer" from "to workshop participants"?

### ISSUE THREAD

**Issue by karinlag** [swcarpentry/instructor-training#291]
I am reading through the materials again now, and I am sometimes left wondering who the text is meant for. Most of the time it is clear that this is something that the trainer should say to the workshop participants, but sometimes it's difficult to separate. One example is 02-introduction. I think the top part is "to trainer", but as it stands now it is not quite clear, IMO.

**Comment by ErinBecker** [comment]
@karinlag I'm happy to take this on in the next few work cycles. Please let me know if anyone would like to work on this together.

**Comment by karinlag** [comment]
@ErinBecker how about recruiting those who will be teaching the next couple of months? They kind of have to read through the material anyhow :smile:

**Comment by ChristinaLK** [comment]
I think some of this can/should be addressed by re-structuring of instructor notes per #385

**Comment by ErinBecker** [comment]
Closing based on duplicate here: https://github.com/ErinBecker/instructor-training-reorg/issues/17
