### ISSUE TITLE
Explanation of icons?

### ISSUE THREAD

**Issue by karinlag** [swcarpentry/instructor-training#292]
Is there a guide to the icons somewhere that I've missed...? Just want to be sure that I understand things correctly.

**Comment by ErinBecker** [comment]
@karinlag Can you give an example of one of the icons you're referring to? I'm not sure what this is in reference to. Thanks.

**Comment by karinlag** [comment]
For instance, we have a bell for exercises, a pin for what I believe to be additional material (although that one breaks a bit for the  Novice and Formative assessment module, a lot of it is under a pin), and so forth. I am sure there is a guide somewhere in the code that renders the pages, but it should be more explicit.

**Comment by ChristinaLK** [comment]
This should really be in the lesson template, opening an issue there.

**Comment by karinlag** [comment]
As long as there's a pointer to that from the instructor-training repo somewhere I'm good with that. IMO, these should be self-documenting.
