### ISSUE TITLE
how reliable is education research?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#293]
A reader writes:

> So, I kept going after I finished the “How learning works book” and have started reading the literature cited in the cook. So far, the five that I have read (which were some of the most cited in the book) are all really just paired t-tests. 
> 
> I like what the book says, I want to agree, but as a scientist that knows a little about stats I am concerned that we are building a house on a foundation of sand. 
> 
> Do you have thoughts on this?

To which Greg replied:

> I think ed research is waking up to the fact that they have the same problem that a lot of psych research has (e.g., http://science.sciencemag.org/content/349/6251/aac4716 and http://www.nature.com/news/over-half-of-psychology-studies-fail-reproducibility-test-1.18248).  I suspect this might be because a lot of ed researchers have backgrounds in psych, or learned their stats and experimental methods in psych classes, but the good news is, people are waking up to the problem (e.g., http://edr.sagepub.com/content/early/2014/07/23/0013189X14545513.full.pdf+html, https://psychbrief.com/2015/12/21/thats-not-quite-right-stereotype-threat/).  I haven't seen any studies yet focused solely on shortcomings in the stats used in these studies, but as funding agencies start to insist on making raw data accessible, I'm hoping we'll see standards go up.  And yeah, that means we'll have to change what we teach, but that's one of the reasons we keep our notes electronic.

**Comment by ErinBecker** [comment]
@gvwilson Closed due to lack of activity. If there are specific actions you'd like to take based on this feedback, please re-open.
