### ISSUE TITLE
a note for instructors

### ISSUE THREAD

**Issue by sarahsupp** [swcarpentry/instructor-training#3]
On today's debrief (Jan 14) we discussed helpful hints on teaching methods for new instructors. 

I'm not sure where this should go, maybe in workshop.md, but we should add a note to suggest keeping the lesson "script" or instructor's notes on a separate screen, such as a tablet. This way, learners aren't distracted by seeing the instructor's notes, and the instructor doesn't have to switch between screens to see what comes next. I like to use an iPad or tablet for this purpose, and the projected screen that the learners can see only contains the live code or instructions for challenges.

Another comment was that if there is the capability for 2 projected screens, you can have one for the live code, and another that shows the example scripts (for reference) or instructions for challenges.

**Comment by gvwilson** [comment]
Put into training course in https://github.com/swcarpentry/training-course/commit/4214556654428a14a5d98293b908e7dbf1c38f02
