### ISSUE TITLE
"connection not secure" error message

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/instructor-training#308]
A student enrolled in an upcoming instructor trainer workshop sent me the following email:

"Firefox does not seem to be thrilled about my trying to connect to the “Starting with Data in R” or “Starting with Data in Python” lessons. When I click on those links below, I get: “Your connection is not secure. The owner of datacarpentry.org has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.” The link for the “Basic Queries in SQL” lesson works. I’ll try another browser if it’s just on my end, but I thought I’d mention it in case others were experiencing the same problem."

The links in reference can be found can be found on [the setup page](https://github.com/swcarpentry/instructor-training/blob/gh-pages/setup.md) of the main lessons repo and on [our course website ](https://christinalk.github.io/2016-09-28-ttt-sesync/) and in in an email I sent. 

Any ideas what the problem is?

**Comment by gvwilson** [comment]
I'll dig into it tonight.
G

**Comment by gvwilson** [comment]
Part of this is in the SESYNC training website, and is fixed (I hope) by 
https://github.com/ChristinaLK/2016-09-28-ttt-sesync/pull/3.

However, I'm unable to reproduce the error on the main lessons repo - 
can you please check?

**Comment by ErinBecker** [comment]
@gvwilson @ChristinaLK Can you please confirm this issue is fixed and close?

**Comment by ChristinaLK** [comment]
I think it's fine now.
