### ISSUE TITLE
rubric for live coding?

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/instructor-training#313]
- help people give "negative" feedback
- set expectations

**Comment by ChristinaLK** [comment]
Rayna and I made this up and used it today: 

* Presentation: 
    * Did the presenter verbalize their typing/thoughts?  
    * If so, what was said that was helpful for understanding?  What was distracting?  
    * If not, what could they have said?  
    * Was the typing aligned with the words the instructor said? Was any code typed that wasn't explained?
* Content: 
    * What was useful or well-organized about the content?
    * Were any concepts / conceptual links skipped? 
* Pacing:
    * Did the instructor talk/type too fast or too slow?

**Comment by lexnederbragt** [comment]
I made my own and have these additional aspects I pay attention to:

Was the presenter:

* Mirroring learner’s environment
* Sticking to the material
* Embracing mistakes, if any
* Use of Illustrations, if applicable
* Avoiding being disturbed (not likely to happen in 5 minutes, but you never know)

**Comment by raynamharris** [comment]
Did either of these rubrics get added to the lesson or the instructor notes? One or both would be useful. They could be added as callout boxes. @lexnederbragt @ChristinaLK

**Comment by gvwilson** [comment]
@raynamharris I don't think a rubric has been added - can you please merge these two suggestions into a PR, and either @lexnederbragt or @ChristinaLK could review and merge.

**Comment by lexnederbragt** [comment]
Sorry, I forgot to link to #345, which has is a PR for a checklist and rubric for teaching demos

**Comment by ErinBecker** [comment]
@lexnederbragt @gvwilson @raynamharris It looks like this has been incorporated, but I'm not sure. Could you please confirm that this issue has been addressed and close?

**Comment by lexnederbragt** [comment]
All good, see https://swcarpentry.github.io/instructor-training/guide/#demo-sessions.

**Comment by orchid00** [comment]
I arrived here looking for the demo rubric, which has now been moved to http://carpentries.github.io/instructor-training/demos_rubric/

in case anyone else is looking for it, it's currently a PR in the handbook
