### ISSUE TITLE
introduction to the carpentries

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/instructor-training#314]
Was touched on in #222 , there is a need for a brief 10 min SWC/DC overview at the start of Day 1 to establish context.  Diving right into actionable material isn't much use if people are confused about the context of the training.  

There's already some text in the "welcome" section; one suggestion (per @raynamharris) is to move the history/venn diagram from "the carpentries" to the welcome section.

**Comment by ErinBecker** [comment]
@ChristinaLK could you please clarify if this is still an open issue? If so, I'm happy to take this on during the next few working cycles.

**Comment by ChristinaLK** [comment]
Yes, I'd still like to do more of an intro.  @gvwilson likes to dive right into the material asap but I think a short introduction is necessary, esp. as we have more trainees who are less familiar with the carpentries.  

I actually have a draft of a one-page handout, but haven't had a chance to work on it recently...
Another option would be a standard opening slide deck, which I *do* have a version of...

**Comment by raynamharris** [comment]
Given the feedback from my most recent workshop, I'm really beginning to think that the Carpentries and Carpentry Teaching practices would be very well received at the beginning of the workshop....maybe right after Tracy's introductions lesson. This would then provide the foundation for all the teaching pedagogy and everything else.

**Comment by lexnederbragt** [comment]
@raynamharris This is an important suggestion and perhaps deserves it's own issue?

**Comment by raynamharris** [comment]
Thanks @lexnederbragt maybe this is worth a separate issue, but I think for now I'll see if we discuss this again at our next in person meeting. Might be easier to get feedback in a group discussion since a lot of instructors have been teaching recently and can weigh in on thoughts.

**Comment by karinlag** [comment]
I think @raynamharris 's suggestion is a good one. That also establishes a common base for all of our students, regardless of whether they have been to a workshop or not. But, we do have to figure out how it would work.

**Comment by ErinBecker** [comment]
This seems related to the discussion about organizing our curriculum into modules (https://github.com/swcarpentry/instructor-training/issues/430). Can we move this discussion over there? Thanks!
