### ISSUE TITLE
More clearly define lessons and sections for teaching demos

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/instructor-training#317]
At my most recent teaching demo session, a trainee told me that the section I had assigned to him was part of the 'supplementary lesson material', and that he was told at his checkout discussion session not to include when preparing for the demo. The lesson was http://swcarpentry.github.io/r-novice-inflammation/ which indeed has lessons with 'supp' in the url (09 - 15, see https://github.com/swcarpentry/r-novice-inflammation/tree/gh-pages/_episodes).

It didn't matter too much at the time, I picked a different part and all went well. But I think we perhaps need a more restricted list of lessons with sections that can be, and won't be a part of the demo, so that we all (including discussion session hosts) communicate the same message to trainees.

**Comment by ChristinaLK** [comment]
+1 someone once asked me if they needed to prepare *all* of the R lesson, or if they could focus on either the first or second half.

**Comment by karinlag** [comment]
On 15.10.2016 00:22, Christina Koch wrote:
> +1 someone once asked me if they needed to prepare /all/ of the R
> lesson, or if they could focus on either the first or second half.

I also got this question recently, and an adjunct to this was what a 
"lesson" was. I think for some people, it might not be entirely clear 
that it is the whole module and not just one section of a module which 
is a lesson.

hmm... maybe we should think of replacing the word "lesson" with 
module...? Hm.


karin

**Comment by ErinBecker** [comment]
Closed with https://github.com/swcarpentry/instructor-training/commit/466d94cce2f41d27c5809e614834e91590287d8b
