### ISSUE TITLE
Should we draft a set of guiding principles?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#319]
During a recent Library Carpentry call, Gail Clement suggested that instructors be asked to agree to a set of guiding principles for workshops:

> The Library Carpentry community have established a set of principles that we ask every trainer to agree to if they are running a workshop under the Library Carpentry moniker. These are:
> - I agree that to use one or more of the Library Carpentry modules in my Library Carpentry workshops.
> - I understand that the secondary learning outcomes of Library Carpentry workshops are as important as their stated goals. These include (but are not excluded to) learners a) being introduced to the value of non-proprietary file formats, good data management, peer-to-peer learning, not always using GUIs, computational approaches to working with library data; and b) feeling more confident to admit what they don't know, collaborate with developers, pursue further self-directed learning.
> - I agree to support and encourage learners and I endeavour to ensure that attendees have an enjoyable and fulfilling experience.
> - I agree to honour the Software Carpentry code of conduct.
> - I am aware that as Library Carpentry grows, it has an ambition for the lead instructor of every Library Carpentry workshop to have undergone Software/Data Carpentry instructor training. I am aware that by becoming a Software/Data Carpentry approved trainer I can help grow and enrich the Library Carpentry community. Having therefore been a trainer at a Library Carpentry workshop, I agree to consider becoming a Software/Data Carpentry approved Instructor.

The American Youth Soccer organization has a similar set of principles [1], and so do some other organizations.  Would we like to adopt such a set of principles for Software Carpentry and Data Carpentry instructors?  If so, who would like to take the lead on drafting them?

[1] http://www.ayso.org/Assets/Volunteer+Descriptions/volunteer_coach.pdf

**Comment by mkuzak** [comment]
+1 I like it, it makes it clear what an instructor is committing to.

**Comment by JasonJWilliamsNY** [comment]
I think a clear and concise statement of our principles is helpful - people should know if they agree with them (or not) at the very beginning. I might pay attention to trying to order them in some way. In the end there must be a clear difference between what 'Software/Data Carpentry" instruction is, and other brands, or simply teaching 'how to code.'

**Comment by karinlag** [comment]
On 17.10.2016 19:03, Jason Williams wrote:
> I think a clear and concise statement of our principles is helpful -
> people should know if they agree with them (or not) at the very
> beginning. I might pay attention to trying to order them in some way. In
> the end there must be a clear difference between what 'Software/Data
> Carpentry" instruction is, and other brands, or simply teaching 'how to
> code.'


I am also a +1 to this, but we need to be careful to a. not push anybody 
away (who we don't want to push away) and b. not sound like a cult.

karin

**Comment by ChristinaLK** [comment]
Revisited in #349
