### ISSUE TITLE
Increase emphasis on "no learner left behind" techniques?

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/instructor-training#322]
One of the living coding top tens is "no learner left behind" (see [live coding episode](https://github.com/swcarpentry/instructor-training/blob/gh-pages/_episodes/13-live.md)). Should this also be emphasized during the [SWC/DC practices episode](https://github.com/swcarpentry/instructor-training/blob/gh-pages/_episodes/15-practices.md) to highlight its importance?  

Also, should this be emphasized during instructor trainer training and/or in the instructor notes for TTT?

**Comment by ErinBecker** [comment]
Closed due to inactivity.
