### ISSUE TITLE
emphasizing post-workshop assessment

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/instructor-training#323]
Eh, I accidentally committed to the repo rather than creating a branch to merge (yikes) see 3cccc3a907f0668cef06b76f124670da613db94f

Anyways, I would like to make the assessment much more explicit, rather than written as an (optional) challenge. I think that if 100% of the time we have instructors-in-trained complete assessment then more of our instructors will remember to distribute the assessment during their workshops. 

Thoughts @tracykteal @JasonJWilliamsNY?

**Comment by tracykteal** [comment]
Agree! Great idea both for getting feedback from instructor training and from emphasizing the importance of the surveys in the workshops they go to teach. 

We can even give the 'why take the survey' spiel that they would use in their workshops.

**Comment by lexnederbragt** [comment]
@tracykteal Which 'spiel' is that?

**Comment by tracykteal** [comment]
Well, there is the minor detail that we have to make one. I think we probably all have our own that we use. It would probably be good to write one down instead. Would the instructor training materials be a good place to put some text?

**Comment by ErinBecker** [comment]
Thanks for bringing this up @raynamharris. I just checked and the post-training assessment is no longer an optional exercise, but is part of the afternoon wrap-up from day 2. We've been getting good response rates from the survey, so I think folks are remembering to do it. Ok to close this issue?
