### ISSUE TITLE
Comparison with Open Data Institute's "Train the Trainers"

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#326]
The Open Data Institute's "Train the Trainer" material is at http://theodi.org/courses/train-the-trainer, and their assessment criteria are laid out at https://docs.google.com/document/d/1HpQnX2uB0e462C_r76jkGZQ4j_dKnBgWk3MPrQ2af4U/.  If any trainers-in-training are looking for a project, a comparison of their work with ours, and an outline of what we could borrow (or better yet, how we could collaborate) would be very welcome.

**Comment by jarekbryk** [comment]
Hi Greg, is this something you would still be interested in? I could do it but my experience with SWC is very limited (just started). On the other hand I think I can have a useful perspective on their assessment approach as it is quite similar to what is done for assessing teaching in higher education in the UK (see https://www.heacademy.ac.uk/recognition-accreditation/hea-fellowships) - and this is the biggest difference between SWC and ODI as far as I can see.

**Comment by ErinBecker** [comment]
Closed due to lack of activity.
