### ISSUE TITLE
add material on introductions

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/instructor-training#327]
from: https://github.com/tracykteal/instructors-introduction

**Comment by raynamharris** [comment]
Thanks @ChristinaLK. Is there a way to squeeze in an intro exercise at the end of motivation and demotivation to wrap up the morning of Day 2? I think this fits very easily with the topic, and its a nice way to note end the morning on a down note (with the what demotivates students).

**Comment by garrettgman** [comment]
+1 @raynamharris. 

This would be a great candidate for positive example / anti-example videos.

**Comment by ChristinaLK** [comment]
I agree w/ Tracy's email that this would go well at the end.  I feel like we should finish with some concrete tools to help them checkout/get ready for their first workshop + talking about the organizations/lessons/introduction all seems of a piece to me.  

Right now, the afternoon of day 2 after the break is actually fairly free.  We could include the introductions material there and then the trainer could choose whether to do an activity of building a website and/or doing introductions as breakout sessions.

**Comment by ErinBecker** [comment]
Closing this issue, as it is now part of the [episode cleanup checklist](https://github.com/ErinBecker/instructor-training-reorg/issues/45)
