### ISSUE TITLE
Develop checklists

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/instructor-training#328]
https://github.com/swcarpentry/amy/issues/1054 and other things made me realise it would help if we had checklists:
- TTT workshops (e.g., I didn't know we are supposed to add 'pass/fail' to attendees in AMY after the workshop)
- discussion sessions
- homework evaluation (I currently have no idea who does what and how)
- teaching demo's (see #313 and #317)

**Comment by lexnederbragt** [comment]
Teaching demo's addressed in #345

**Comment by ChristinaLK** [comment]
Christina's take: I really like checklists that are organized by "one month ahead, one week ahead, day before" etc.  Some ideas: 

Month before
- [ ] Receive email confirmation + connection w/ hosts from Maneesha
- [ ] start discussion w/ fellow trainer(s) about who is teaching what
Two weeks before
- [ ] Arrange meeting between trainers + representatives from host to discuss expectations, attendees, needs
- [ ] Create training page
- [ ] Create auxiliary stuff (etherpad/google doc, any forms you want to use)
- [ ] Confirm who is teaching what, start preparing material
Week before
- [ ] Arrange test of videoconferencing (if online)
- [ ] Test videoconferencing
- [ ] Send reminder email to participants w/ connection info, etc. (templates in repository)
- [ ] Finish preparing to teach material
- [ ] Email trainers list to see if anyone wants to sit in, provide connection info
Day before
- [ ] Final reminder to participants

**Comment by ErinBecker** [comment]
@maneesha recently sent around a partial Trainer manual that includes some of these items (https://docs.google.com/document/d/1Tq_b3bZYBqyQf73qqqb4VSMXRDHrDuZH7Q4pweI-6WE/edit). Requesting edit access to add some of the detail discussed here, but @maneesha is on vacation until the 31st.

**Comment by ErinBecker** [comment]
See discussion here (https://github.com/swcarpentry/instructor-training/issues/385). Closing here and incorporating into checklist.
