### ISSUE TITLE
Don't say "just"

### ISSUE THREAD

**Issue by duffymeg** [swcarpentry/instructor-training#33]
In the "Things You Shouldn't Do in a Workshop" section, I think it would be good to add that instructors shouldn't tell participants to "just" do something (e.g., "just go to the command line and type..."). This was brought up in the instructor training I participated in, and I thought it was a really important point. If someone says "just do X" and you can't do it, that's pretty demoralizing.

**Comment by gvwilson** [comment]
@duffymeg please review #34.
