### ISSUE TITLE
Trainers should not certify people from their own institution

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#332]
In order to avoid conflict of interest, trainers should not certify people working at their home institutions.

**Comment by lexnederbragt** [comment]
I propose to do this as part of #328

**Comment by gvwilson** [comment]
:+1:

**Comment by ErinBecker** [comment]
@lexnederbragt Could you confirm whether this has been added to the documentation?

**Comment by ErinBecker** [comment]
Closed due to redundancy with #384
