### ISSUE TITLE
Rubric for applications for open instructor training

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#336]
Please vote by leaving :+1: or :-1: on this issue.  (Click on the smiley face in the upper right above this text to leave an emoji, or add a comment.)

----

## Background

1.  There are many more applications than places, so we have to select people somehow. As an open organization, we should make our criteria explicit and open.

2.  You can view the existing application form at https://amy.software-carpentry.org/workshops/request_training/.

## Rubric

1.  Clearer explanation of what "Group Name" means (move help text up).
    1.  "If you are applying at the same time as friends or colleagues, pick a name for your group (e.g., the name of your institution) and fill that in, and we will try to put you in the same training class."
2.  Location:
    1.  Award +1 for outside Europe/UK/US/Canada/Australia/New Zealand
    2.  *Or* award +1 for being in smaller/remote/less affluent institution within EU/UK/US/Can/Aus/NZ
    3.  We will have to evaluate this manually: online university rankings and listings of school sizes won't do what we want.

3.  Domain
    1.  Award +1 for being in economics or social sciences, arts, humanities, or library science (domains where we wish to expand).

4.  Gender
    1.  Keep question as is (female, male, other, prefer not to say).
    2.  Do *not* score directly on this.

5.  Add a new question: Are you a member of one or more groups that are under-represented in computing (e.g., women, minorities, LGBT, disabled)?
    1.  Options are "No" and "Yes - specify [___]"
    2.  Score manually.
    3.  Help text will remind them that their answers are kept private under the terms of our data privacy policy (with link), and will not be shared with anyone without their explicit prior consent.

6.  New question: "Have you participated in other volunteer or non-profit groups or organizations?  (Example could include youth sports, clubs, religious or civic organizations, etc.)"

7.  Previous involvement
    1.  Change question from checkboxes to "How often have you..." and allow them to fill in numbers.
    2.  Score +1 for each previous involvement up to a maximum bonus of +3.

8.  Previous training in teaching
    1.  Change "Previous training in teaching" to "Previous training as a teacher or instructor".
    2.  +1 for "a certification or short course" or "a full degree"

9.  Previous experience in teaching
    1.  Change options to "a few hours", "a workshop", "TA for full course", or "primary instructor of full course"
    2.  Award +1 for "TA for full course" or "primary instructor for full course".

10. How frequently do you program?
    1.  Change wording to, "How frequently do you work with the tools that Data Carpentry and Software Carpentry teach, such as R, Python, MATLAB, Perl, SQL, OpenRefine, and the Unix Shell?"
    2.  Award +1 for "every day" or "a few times a week".

11. How often would you expect to teach?
    1.  Applicants must tick a box agreeing to teach within 12 months of training as part of the application process.
    2.  The purpose of this question was therefore to identify people from partner sites who are taking the training, but don't intend to teach.
    3.  We have decided *not* to have people from partner sites fill in this form, so the "Not at all" option can be removed.
    4.  Remove "Primary occupation" option as well - subsumed by "Several times a year".

12. Discretionary
    1.  Anything from -3 to +3 based on awful or awesome answers in the free-text boxes, to the question about smaller/more remote institutions, diversity, etc.

**Comment by maneesha** [comment]
Q4: Why are we asking about gender if we are not scoring on it?  Minority representation is included in the next question.

Q5: Is this wording consistent with laws in some countries explicitly prohibiting asking about demographic background?

Q10:  Perl??  Also include Git. 

Q12: Applicants will already have gotten points for remote institutions & diversity so I'd suggest these points be awarded only for awesome or awful things beyond what's already been covered.

**Comment by rgaiacs** [comment]
Q4: Why are we asking about gender if we are not scoring on it?

Because this is important for statistics. :-)

**Comment by gvwilson** [comment]
On the one hand, we can get stats for actual instructors from their AMY 
profiles once they've qualified.  On the other, I'd like to know if some 
groups of people are more or less likely to complete.

**Comment by maneesha** [comment]
I am very reluctant to have anything in there that's not explicitly being rated.  If we are collecting anything for statistical purposes only, that needs to be made clear and be separate from the rest of the application.

**Comment by ErinBecker** [comment]
I'm concerned about the amount of work required to manually evaluate point 2ii (remoteness/affluence/etc of institution). Why not have a checkbox asking whether the respondent's institution meets any of these criteria? We can then go through the ones who answer "yes" and manually check those, rather than having to research all of the institutions of the people who apply. This could get very time consuming otherwise.

**Comment by allegravia** [comment]
Q2. I share Erin's concern about the amount of work required to manually evaluate point 2ii. I also agree with the solution she proposed.
Q3. Why not including (school) education? (Perhaps this is just my personal wish...)
Q5. Is this question meant to be mandatory? If yes, answering might be difficult for some; if no, it might become difficult to compare people who answered YES (and get a positive score) with people who didn't answer. 
Q6. What is the precise aim of this question? What exactly do you want to capture?
The range of existing volunteer or non-profit groups is so large - and the definition of "volunteer or non-profit group" prone to personal interpretation - that a simple yes/no may be not much informative (I would expect the great majority of respondents to say yes). It would be more helpful to capture "to what extent". Why not proposing a list of possible groups (including "Others" + textbox)?
Q8. I fully agree with Erin's comments on this point (including flipping Q7 and Q8).
Q10. I agree with the rewording proposed and yes, definitely add Git.

**Comment by ChristinaLK** [comment]
@allegravia I proposed Q6 to get at demonstrated past commitment to a volunteer org, which would (hopefully?) be a potential indicator of future involvement in SWC/DC.  I like your suggestions - I mainly didn't want to write that whole list myself unless other people thought it was a useful question to ask. 

Does everyone think that past commitment to a volunteer org is worth measuring/scoring?  If so, I'll try to draft a better version of the question, incorporating Allegra's suggestions.  Otherwise, we can just take the question out.  Thoughts?
