### ISSUE TITLE
Example of using brainstorming.

### ISSUE THREAD

**Issue by mkuzak** [swcarpentry/instructor-training#340]
Add to notes example of using brainstorming in the workshop.

I've seen this done by @apawlik in data carpentry workshop:
At the start of data carpentry spreadsheet lesson, the instructor asks learners to download a spreadsheet and to discuss in pairs all the "messy" aspects of the dataset and how it can be "cleaned up". After all pairs finished the instructor can collect on the whiteboard all the problems learners came up with and discuss how to address them. That way the instructor can assess what learners already know and what needs to be filled in. It's not formal brainstorm session, but it will depend on the instructor if he will do it more in exercise-like or brainstorm-like style.

**Comment by ErinBecker** [comment]
If anyone feels this would incorporate well into the re-organized materials, please add a comment (and/or a PR :-)). Else, I'll close this based on inactivity when we merge the reorganized materials later this month.
