### ISSUE TITLE
motivation and demotivation, which should be discussed first?

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/instructor-training#353]
So, after one workshop, I got some "one down" comments that the demotivation session left the learners on a downer right before lunch. 

I wonder if we should first talk about demotivation and then talk about motivation so that we end on a positive note. Alternatively, maybe there is simply a better way to return to motivation at the end and emphasize the positive ways that we can counter act demotivation.

Thoughts?

**Comment by gvwilson** [comment]
The last two times I've taught, I've moved the motivation/demotivation section to immediately after lunch on day 2 - that seems to help.

**Comment by raynamharris** [comment]
Okay. Seems like it might be a big task to tackle reordering. I saw we leave it as is for now and @ChristinaLK  can decide later if we want to attempt another reorganization.

**Comment by karinlag** [comment]
I am teaching this one tomorrow, and will give the flipping a go. Will report back.

**Comment by raynamharris** [comment]
This issue was inspired by one learner's comment that we ended on a sad note. After teaching this a few times with different instructors, I really like the current order, so I'm closing this issue.
