### ISSUE TITLE
Link to detailed explanation about the git contribution model from checkout

### ISSUE THREAD

**Issue by arokem** [swcarpentry/instructor-training#356]
Comment from an attendee in the recent PNNL TTT workshop. Even if you know git/Github well, you don't necessarily know what workflow model is used. 

Something like the explanation we have here might be helpful:

http://nipy.org/dipy/devel/gitwash/git_development.html

**Comment by mkuzak** [comment]
I believe this is covered in `CONTRIBUTING.md`. Exact choice of GitHub flow branching model and and link to more detailed explanation is also there. Here what is r-novice-infalmation lesson:
https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/CONTRIBUTING.md
and the branching model section:
https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/CONTRIBUTING.md#using-github

**Comment by ErinBecker** [comment]
Closed with https://github.com/swcarpentry/instructor-training/pull/418
