### ISSUE TITLE
Include this cartoon about feedback

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#357]
<http://www.lunarbaboon.com/comics/feedback.html>

**Comment by ErinBecker** [comment]
@gvwilson I like this cartoon and think it would be a good substitute to the feedback cartoon we currently use, which is somewhat of a downer. Could you please make the switch?

**Comment by lexnederbragt** [comment]
Yes, the current one is a downer, but it is quite realistic (having just been through such an experience). Can we use both?

**Comment by ChristinaLK** [comment]
I'm okay with removing the current one, but I think it brings up an important topic to address (the emotional aspect of receiving feedback), so I'd want to make sure we still have supporting text to bring that up.

**Comment by raynamharris** [comment]
Is it okay to have both? I really like both a lot! And I think having both would very much represent what I try to convey in this portion of the curricula.

**Comment by mkuzak** [comment]
+1 for both

**Comment by maneesha** [comment]
I like both comics.  I've been a fan of Lunar Baboon for years.  There is one word in the LB comic that I try to use very carefully in the context of how I teach: the word "but."

Think about the impact of hearing "Good use of color but I think it needs more detail" compared to hearing "Good use of color, and here's a place you could add in more detail."  Using the word "but" implies that the second clause in the sentence contradicts the first.  Using the word "and" implies the second clause in the the sentence enhances the first.  

When positive feedback is followed by the word "but" it's often what follows the "but" that people hear and remember - and what sticks with them when they go to bed (like in the current comic).  

I like the idea of using both, especially if we can talk about them together in the context I've described above.

**Comment by lexnederbragt** [comment]
Thanks, Maneesha, this is so useful! I had never realised this aspect of the 'sandwich' approach (put the critique between positive feedbacks). Next step: try to implement saying 'and' instead of 'but'...

**Comment by ErinBecker** [comment]
Closed with https://github.com/swcarpentry/instructor-training/pull/419
