### ISSUE TITLE
Be clear about admin fees and related rules

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#36]
Instructor training needs to be much clearer about use of the 'instructors' mailing list, admin fees, etc.

----

Our policy with self-organized workshops is that you are not allowed to use central resources to find instructors unless you are paying our workshop administration fee for the workshop. If you would like to pay the workshop administration fee we will be happy to help you find instructors. This instructor matchmaking is exactly why we employ folks (at a cost to us) that develop software for workshop organizing and are able to match the most appropriate instructor to the workshop and its audience.

**Comment by karinlag** [comment]
On 03.12.2015 15:57, Greg Wilson wrote:
> Instructor training needs to be much clearer about use of the
> 'instructors' mailing list, admin fees, etc.
>
> ------------------------------------------------------------------------
>
> Our policy with self-organized workshops is that you are not allowed to
> use central resources to find instructors unless you are paying our
> workshop administration fee for the workshop. If you would like to pay
> the workshop administration fee we will be happy to help you find
> instructors. This instructor matchmaking is exactly why we employ folks
> (at a cost to us) that develop software for workshop organizing and are
> able to match the most appropriate instructor to the workshop and its
> audience.

I keep thinking of it this way:

admin fee: help with finding instructors

membership: getting instructors trained, and getting the lesson material 
developed

Karin

**Comment by gvwilson** [comment]
A pull request adding this to the notes would be very welcome. What else is missing about operations?

**Comment by apawlik** [comment]
Um, What should I do with the PR 247 in the internal board repo?

**Comment by gvwilson** [comment]
Once it's merged, a PR against site's workshops/operations.html would be 
very useful - we'll reference that from the instructor training notes 
(rather than duplicating stuff).

**Comment by gvwilson** [comment]
Ping @apawlik @karinlag - is there something stable in the board repo we can link to?

**Comment by karinlag** [comment]
On 21.03.2016 19:46, Greg Wilson wrote:
> Ping @apawlik <https://github.com/apawlik> @karinlag
> <https://github.com/karinlag> - is there something stable in the board
> repo we can link to?

How about

https://github.com/swcarpentry/board/blob/e735456ee521f59a21f72a6b4678453b177c09d2/workshops.md

?

Although, this is pre-hike in price, so that would have to be updated.

Karin

**Comment by gvwilson** [comment]
Yeah - I should hold off until everything is settled for SWC and DC 
prices...

**Comment by apawlik** [comment]
There is work in progress on wording and rules for self-organised workshop so suggest waiting until it's agreed and published. On a side note - membership does not exclude admin help.

**Comment by gvwilson** [comment]
link to http://software-carpentry.org/workshops/request/

**Comment by karinlag** [comment]
On 28/04/16 21:19, Greg Wilson wrote:
> link to http://software-carpentry.org/workshops/request/

... aren´t also self organized workshops supposed to report # of learners?

Karin

**Comment by gvwilson** [comment]
@jduckles? @maneesha?
