### ISSUE TITLE
broken links to lessons

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/instructor-training#369]
The links to the suggested lessons for the demo session checkout are broken :(

https://github.com/swcarpentry/instructor-training/blob/gh-pages/_extras/guide.md#example-starting-points-for-demos

**Comment by gvwilson** [comment]
They're correct when the rendered page is viewed at 
http://swcarpentry.github.io/instructor-training/guide/ - the raw 
Markdown uses a variable reference.

**Comment by raynamharris** [comment]
Ah okay. Thanks for clarifying.  Next time I access this page from the internet not github.
