### ISSUE TITLE
Up and down in Live Coding module

### ISSUE THREAD

**Issue by karinlag** [swcarpentry/instructor-training#375]
When it says Up and Down, what are we supposed to do then? I get the impression that we are doing a "one person says something good, one person says something bad, and that they all have to be unique", but it is not specified. Am I on the right track?

**Comment by lexnederbragt** [comment]
Check the bottom part of https://swcarpentry.github.io/instructor-training/12-summarize/.

**Comment by karinlag** [comment]
Ah, I then take that to be the normal "one good, one bad" thing.
