### ISSUE TITLE
Motivation section promises list (but no list)

### ISSUE THREAD

**Issue by kcranston** [swcarpentry/instructor-training#376]
The first paragraph in the [strategies-for-motivating-learners](https://github.com/swcarpentry/instructor-training/blob/gh-pages/_episodes/16-motivation.md#strategies-for-motivating-learners) section states: "How Learning Works contains this list of evidence-based methods to motivate learners" but does not actually present the list. Reading through the motivation chapter of HLW, it is unclear to me what list we are talking about. It the current form, this section of the lesson contains no strategies for motivating learners.

**Comment by kcranston** [comment]
Scrolling through a previous commit, I see [this mention of a checklist](https://github.com/swcarpentry/instructor-training/commit/ca141b78a2fd38e80451a3944c80c6088cd0d824#diff-59c2eb81f15ab504e4f042127048f01aL158) deleted, but I am still not sure where the checklist lives / lived.

**Comment by ChristinaLK** [comment]
Ah, I remember this.  There used to be a list of things that motivate people.  @ErinBecker let me know if you have trouble finding it or want me to take this.

**Comment by ErinBecker** [comment]
@ChristinaLK, yes please. I've looked around but haven't been able to find it.
