### ISSUE TITLE
Carpentries module needs updating regarding no-show policy

### ISSUE THREAD

**Issue by karinlag** [swcarpentry/instructor-training#377]
This is regarding how early instructors can cancel a workshop they have signed up for.

Details of current policy in:

https://github.com/swcarpentry/board/blob/master/minutes/minutes-2016-11-30.md

Motion #2016-11-30/4

**Comment by ErinBecker** [comment]
@karinlag DC and SWC have slightly different no-show policies. I'm happy to reference both in the instructor training curriculum, but this may be confusing. @tracykteal @maneesha what do you advise?

**Comment by ErinBecker** [comment]
Ah, I see the joint policy now. Thank you @karinlag , I will update.

**Comment by ErinBecker** [comment]
Closed with https://github.com/swcarpentry/instructor-training/pull/420
