### ISSUE TITLE
Carpentries module: where can I find a pre-assessment form for critique

### ISSUE THREAD

**Issue by karinlag** [swcarpentry/instructor-training#379]
SSIA.

**Comment by ErinBecker** [comment]
@karinlag I'm not sure what you mean by this? Could you please explain?

**Comment by karinlag** [comment]
One of the carpentries module's exercises is to go look at the pre-assessment questionnaire and critique it. Thus it would be helpful to have a link to the pre-assessment questionnaire so that it's easy to find it so that we can look at it.

**Comment by raynamharris** [comment]
I also had to look up SSIA to figure out that it meant subject says it all.

The exercise is at the bottom of this page. http://swcarpentry.github.io/instructor-training/21-carpentries/

I have never used this exercise, and I'm not sure who else has. If we keep this exercise, it might be useful to have a questionnaire with results that has been censored to remove all names. Or, we can scratch the exercise.

**Comment by ChristinaLK** [comment]
I would vote to remove that exercise.

**Comment by raynamharris** [comment]
Okay, how about a quick vote?

Thumbs up to remove exercise
Thumbs down to keep the exercise and add link to actual assessment form

**Comment by mkuzak** [comment]
I've never used it either. I don't mind keeping it and let trainers decide if they want to use it or not.
I think there is a questionnaire which can be viewed but does not get submitted.
