### ISSUE TITLE
Suggestion: insert suggested timing in materials

### ISSUE THREAD

**Issue by karinlag** [swcarpentry/instructor-training#382]
When I was teaching last week, I was struck by the feeling that I had no idea how I was doing timewise with the materials. This especially goes for modules with exercises, I had no idea if I had a little or lots of time left for them. I thus suggest we try to gather together some suggestions for where you should be when in the material. I suggest we ask those that teach for the next few times try to write down once in a while in a module how much time they spent getting there, and how much time they left for exercises. That way we can get some sense of where we should be when.

**Comment by mkuzak** [comment]
@karinlag I had similar issue today, the challenge I see here is timing will highly depend of the setup but we could define upper and lower value. For example:
this exercise takes at least 5 minutes but should not take longer than 10.

**Comment by karinlag** [comment]
@mkuzak sounds like this is needed by more than me then :)

**Comment by raynamharris** [comment]
@karinlag how does this work for adding some time suggestions?

https://github.com/swcarpentry/instructor-training/pull/399

**Comment by ErinBecker** [comment]
Addressed with https://github.com/swcarpentry/instructor-training/pull/422

**Comment by ErinBecker** [comment]
I think it's important to communicate to Trainers that the times given for the exercises and discussions are suggestions and their group may need more or less time for any given portion of the lesson. We don't want to be too prescriptive. I'll make sure to go over this idea with the new Trainers in training, but it's also a good thing to put in the instructor notes. 

These suggested timings should also be modified based on your experiences while teaching. If anyone finds that the timing is way off, please submit a PR or issue to update these time estimates. I hope these help provide a guideline at least.
