### ISSUE TITLE
Rubric for teaching demos

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/instructor-training#394]
We should have a clear rubric for teaching demos so that there is consistency in who is passed/not passed and also to help Trainers feel more confident in their decision to pass/not pass someone.

I have certainly had cases where the trainee obviously failed or obviously passed, but also borderline cases and it would be good to have clear guidelines that we all agree on. 

To get the conversation started, I'll note some things I've been looking for:

Positives:
- slow pace
- explaining things as they do them (e.g. tab complete)
- acknowledging mistakes and being clear about process of self-correction

Negatives: 
- use of dismissive language ("simply", "obviously", "just", "of course")  
- troubleshooting without explaining process  
- significant deviation from the lessons as written
- speaking quickly or unclearly
- covering material quickly

This is by no means a complete list - just a start to get the conversation going. Please add your own "things to look for" and together we'll compile those and assign relative scores/importance to develop our rubric.

**Comment by ChristinaLK** [comment]
For positives
+1 explaining things as they do them
+ 1 explaining mistakes
I'd add: has seen the lesson before and thought about it.  
If someone can think of a more concrete way to evaluate that, let me know!  

For negatives: 
+1 to significant deviation from lessons as written
+1 to rushing that's not just nervousness

**Comment by raynamharris** [comment]
One thing I think about this is that "delivery" seems to be very easy to critique (e.g. "used um a lot", "didn't talk loud enough") but content is much harder to evaluate and critique. So, I am definitely in favor of providing a rubric and/or set up examples content critiques.

**Comment by lexnederbragt** [comment]
A while back I added [this rubric](https://github.com/swcarpentry/instructor-training/blob/gh-pages/files/teaching-demo-rubric.md) (linked to from the [instructor notes](https://swcarpentry.github.io/instructor-training/guide/#during-the-demo)) but that doesn't meet @ErinBecker's idea of positives and negatives. I agree with @raynamharris that some aspects are hard to critique in the short time allotted.

**Comment by karinlag** [comment]
Well... one aspect of this is that as long as they're teaching from our material, it is actually our content that they're delivering. I.e. I don't think we should focus too much on content. I think the delivery is actually what we are evaluating them on. In this context, _how_ they teach is for me the deciding factor, and not what.

**Comment by lexnederbragt** [comment]
I partly agree. I have had cases where the trainee deviated from the lesson, and I always make a point of discussing this with them - they may be doing a good job with it, but I'd like to point out that one has to test deviations very well to prevent falling into som unexpected trap of errors etc.
