### ISSUE TITLE
discrepancy in schedule

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/instructor-training#401]
There is a discrepancy in the schedule that is posted on the [main lessons page](https://swcarpentry.github.io/training-template/) and the schedule that is displayed in the [lesson template](https://github.com/swcarpentry/training-template) and subsequent workshop pages. This should be corrected. 

Workshop template screen shot
![screen shot 2017-03-07 at 8 33 37 pm](https://cloud.githubusercontent.com/assets/7544197/23687701/71007e18-0375-11e7-963e-a346b84398e4.png)

Main lessons page screen shot
![screen shot 2017-03-07 at 8 33 54 pm](https://cloud.githubusercontent.com/assets/7544197/23687715/843820a8-0375-11e7-8e6f-98e6544f0924.png)
![screen shot 2017-03-07 at 8 34 01 pm](https://cloud.githubusercontent.com/assets/7544197/23687717/85ee9b2a-0375-11e7-8450-d697c48313f4.png)

**Comment by arokem** [comment]
See also: https://github.com/swcarpentry/training-template/pull/4

**Comment by ErinBecker** [comment]
The terms module is no longer active and is not showing up in either version of the schedule, so this appears to be fixed. Closing.
