### ISSUE TITLE
Google Drive folder

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/instructor-training#405]
As much as it would be nice to keep everything in the repository, there are a few things that won't fit (e.g. Google Form #397).  Should we create a Google Drive folder for the instructor trainers containing: 

- Template feedback forms
- Basic slide decks (in Google slides)
- A folder for placing Google Docs that were used as the new etherpad?

**Comment by mkuzak** [comment]
I recently had a discussion with @ErinBecker and @steve-crouch and we thought it would be nice if people would put their decks in the drive next to the basic deck. I think people tend to customise their decks. I see the advantage of being able to browse those.

**Comment by raynamharris** [comment]
Christina and I have been using Google Forms to collect annonymous sticky note feedback from learners during the workshop. One of mine is here: https://goo.gl/forms/dE4bYn1pVgrChPiH2

For now, you can copy this, create your own, and add your co-instructors and Erin as collaborators so that y'all can  review the feedback together.

**Comment by lexnederbragt** [comment]
As per https://github.com/swcarpentry/instructor-training/pull/397#issuecomment-286655879, the problem still stands that I cannot create a copy of the form...

**Comment by raynamharris** [comment]
Okay, I think I've solved the problem. 

This link allows you to be a collaborator. https://docs.google.com/forms/d/1Xc87sHqJsJ43X5KU_KORIfv_i4P_1hzSN-mWKd2TXmQ/edit?usp=sharing

Please copy the form and modify it with a name that is reflective of the workshop you are teaching. Use the same form during the entire workshop to have all the feedback in one place. The time stamp will help you see which session the feedback corresponds to.

**Comment by lexnederbragt** [comment]
Great!

**Comment by ErinBecker** [comment]
Added to checklist. Closing here.
