### ISSUE TITLE
Link to instructors' testimonials broken

### ISSUE THREAD

**Issue by mkuzak** [swcarpentry/instructor-training#407]
In [16-motivation](http://swcarpentry.github.io/instructor-training/16-motivation/) in exercise **why do you teach?** there is a link to testimonials from other instructors. It points to [instructor notes](http://swcarpentry.github.io/instructor-training/guide/#testimonials), but there is no testimonials in the notes. I don't know if they have been removed or moved somewhere else.

**Comment by raynamharris** [comment]
The testimonials are under extras 
https://github.com/swcarpentry/instructor-training/blob/gh-pages/_extras/testimonials.md
http://swcarpentry.github.io/instructor-training/testimonials/
