### ISSUE TITLE
Add creating AMY account to intro module

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/instructor-training#411]
Context: Track instructor trainees via an account in AMY.  This account is only created when people complete the training application form (link: https://amy.software-carpentry.org/forms/request_training/ )
Many people have not been completing the application form. This means we cannot track their progress and have to ask them for this information after the fact.  
Solution: The trainers should take 5 minute to ensure that everyone completes this during the training event. 
**Suggestion:** Add the workshop tag "YY-MM-DD-ttt-online" group ID to the welcome email so that everyone knows that they are part of a group and should use that 
 **Suggestion:** Officially add this to the cirriculum if its not already there

**Comment by maneesha** [comment]
Yes -- ideally trainees should be doing this *before* the event so trainers can see who'll be there.   That requires better communication with hosts and is part of the larger strategy of improving how we offer and schedule training events.

That said, if trainees do not complete the application prior to the event, trainers should take time to have them do it.

Question for input following up on @ErinBecker 's suggestion above -- what's the best spot to place this action item in the curriculum?

**Comment by raynamharris** [comment]
It could be added to the section where we go over checkout. 
http://swcarpentry.github.io/instructor-training/checkout/

**Comment by ChristinaLK** [comment]
This could be good at the end of day 1 or start of day 2.
