### ISSUE TITLE
Add note on using closed captions on live coding videos

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/instructor-training#414]
Often there is not good sound in a room, and for accessibility reasons, it would be good to use closed captioning when showing the videos in the 'Live Coding' lesson.

You can turn on closed captioning by pressing the **cc** button on the bottom right of the video. Add to the instructor notes that we should do this when showing these videos.

suggestion from @raynamharris

**Comment by maneesha** [comment]
Commented on the PR: https://github.com/swcarpentry/instructor-training/pull/416

**Comment by ErinBecker** [comment]
Closed with #415 and #416
