### ISSUE TITLE
Add closed captions (subtitles) to live coding videos

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/instructor-training#429]
[Replaces #414. See also discussions in #415 and #416.]

For Software and Data Carpentry instructor training, we use two videos (starring yours truly) to demonstrate do’s and dont’s for live-coding: https://youtu.be/bXxBeNkKmJE and https://youtu.be/SkPmwe_WjeY. We are looking for a volunteer to add subtitles/Closed Captioning to these videos to enhance their accessibility. Instructions how to do this can be found here: https://support.google.com/youtube/answer/2734796?hl=en. (There are automatically created subtitles for the ‘done well’ video, but these are pretty poor).

If this is something you think you could do, please let us know via this github issue.

**Comment by jeremycg** [comment]
Happy to help - will try to get it done Thurs pm and/or Sat am EST.

Might need a proofreader though :)

**Comment by iamc** [comment]
I came into also to volunteer, but Jeremy was faster. @jeremycg , should you find it too much work doing the first one, tell me and I'll do the second one.

In any case I can proofread them.

**Comment by lexnederbragt** [comment]
Wow, thanks both!

I am pasting a few quotes from the [email thread](http://lists.software-carpentry.org/pipermail/discuss/2017-April/005183.html) on the Software Carpentry Discuss list - it may help (or scare you off...)

David Martin wrote:

> As an estimate of time (for willing volunteers) I find it takes me about 6x video length to edit the Youtube automatic subtitling. The quality of the original will depend on how well the algorithm interprets the speaker, and the relative presence of homophones etc. in the spoken text. So I allow about 1 hour to do the editing for a 10 minute video.

Henry Neeman responded:

That's actually impressively efficient.

> In my own experiments, I found that I was doing around 15 minutes of labor per minute of YouTube-autocaptioned video.

**Comment by iamc** [comment]
Yes, I saw the thread. As far as YouTube gives us *anything* synchronized this should be quite easy, and this usually does it properly. We'll see. If not, it won't be much of a job neither, they're really shot (great) videos.

**Comment by iamc** [comment]
BTW, your YouTube subtitle creation instructions link I think refers to videos you own. If I go to your video -> more -> add translation, it says: "The video you requested isn't enabled for community contribution."

Perhaps you should enable this for us to contribute? Otherwise I'd be ok with just a .srt automatic transcription file from YouTube. I'll correct and also  translate it to Spanish and pass it back to you.

**Comment by ErinBecker** [comment]
@lexnederbragt Are you the owner of the YouTube videos? If so, could you please enable contribution from @iamc (@lexnederbragt may need your YouTube account handle or email address).  If you're not the owner, maybe @gvwilson is?

**Comment by lexnederbragt** [comment]
I am the owner. I have now enabled community contributions, let me know if it doesn't work.

**Comment by iamc** [comment]
The second video has what seems auto generated English captions, but no so the first one. I try to generate them (actions -> auto-generate) but I don't get anything, even if the system says "auto generation" complete.

@lexnederbragt , could you please try the auto generation yourself and see if it works for you?

**Comment by iamc** [comment]
OK, video 1 not having subtitles should be due to

> If your video doesn't generate automatic captions, it could be due to one or more of the following reasons:
   ...
    There is a long period of silence at the beginning of the video.

I'll take a look at this.

**Comment by lexnederbragt** [comment]
I find it fitting that the 'done badly' video doesn't allow for auto-generating subtitles :-)

**Comment by jeremycg** [comment]
The first video is done - it says it needs someone to review it, which is probably a good idea :). I'll take a look at the second one now

**Comment by jeremycg** [comment]
Ok and the second is done - much easier with the auto generated start.

The auto transcribe really doesn't like 🦄 or 🦎.

**Comment by iamc** [comment]
Ups. @jeremycg you're faster than me. Thanks!

**Comment by lexnederbragt** [comment]
Great! I'll review soon(ish) - YouTube already sent me an email about the "New community contributed translation or transcription for your video"

**Comment by lexnederbragt** [comment]
Review, lightly edited and accepted! Thanks very much @jeremycg (and @iamc)! Closing this issue.
