### ISSUE TITLE
Organizing episodes into modules

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/instructor-training#430]
I've been thinking a lot about the order of episodes in instructor training. I think the curriculum could benefit from a being arranged into modules around a particular theme that will serve to better motivate the training program and give a rationale for the order and content. Here's what I am thinking:

Part 1: Overview (who we are, our mission/goals, why & what we teach what we teach in TTT)
- Introductions
- ​Overview of the workshop 
- The Carpentries 
- Pedagogical Content Knowledge
- Carpentry Teaching Practices (including Code of Conduct)

Part 2: Educational psychology stuff (in no particular order)​
- Novices & formative assessment
- Expertise & memory
- Cognitive load
- Lessons and objectives
- Motivation and demotivation

Part 3: You in front of the classroom
- Teaching as a performance art
- Live coding
- Introduction to introductions

Part 4: Next Steps
- Checkout procedure
- Overview of volunteer opportunities
- What you are excited about contributing?

What do y'all think about reorganizing around themes? Does it help the flow? Do you have any other questions/comments/concerns?

**Comment by lexnederbragt** [comment]
Although I think the modules make sense, I am worried about the practical implications. For example, currently there is a session on presenting on both days (performance art on day 1, live-coding on day 2), and this structure puts both in the same block. I would vote for keeping them on separate days. Ending day 1 with "Teaching as a performance art" could be solution (and starting day 2 with live coding, as is currently the case), but I worry that it is too late in the day in terms of learners' energy levels/mind-blowness.

I see a benefit in talking about the Carpentries earlier, especially for those not being familiar with them, but would propose to discuss the actual lessons in the afternoon of day 2, *after* Lessons and Objectives.

Part 2 is very theory heavy, and a strong point of the current schedule is that theory is intermitted with other things (less dry). Also, Motivation/demotivation is a often a bit heavy and may leave learners a bit down, it would be better to end day 1 on a high note (I think @gvwilson once proposed to not have it as last lesson before lunch, as it is now, for the same reason)

**Comment by ChristinaLK** [comment]
Agree w/ @lexnederbragt's point re: talking about the lessons later.  I think you want to talk *enough* about the carpentries for people to understand the big picture, but going into lots of details at the very start might be a momentum killer.

**Comment by mkuzak** [comment]
Last time I taught we did performance art and live coding as the first thing on the second day and it went really well. People had a lot of energy.

**Comment by ChristinaLK** [comment]
I am +1 to the ed psych + next step sections
I think I would recast the other two modules as: 

1. teaching culture / learning environment
* Pedagogical Content Knowledge
* Motivation and demotivation
* Carpentries 

2. teaching tools
* Teaching as a performance art
* Live coding
* Introduction to introductions
* Carpentry teaching practices

Those two categories are definitely intertwined (a lot of our culture informs what we *do*) but I would want to specifically call out that this is not generic teaching training -- we've made some assumptions about the kind of learning environment we want people to create at SWC/DC workshops.

**Comment by ErinBecker** [comment]
As we move towards our next lesson publication, I'd like to incorporate this proposed reorganization. I've attempted to re-order the modules in line with these suggestions. Check out [this outline](https://docs.google.com/document/d/1t2W8PKu78KtTX92qdhqclYGljAbLiWfhza7qH6s1088/edit) and please give comments by June 5th. These comments will be taken into consideration moving forward with the lesson publication.

**Comment by ErinBecker** [comment]
This re-organization into modules has been implemented in https://github.com/ErinBecker/instructor-training-reorg, which will be pulled back into this official repo by the end of August. Closing this issue based on this progress.
