### ISSUE TITLE
auto-expand exercises

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/instructor-training#435]
@tracykteal Could you please change the formatting for these lessons so that the exercises auto-show (like in the DC Ecology lessons)? 

Much thanks!

**Comment by jduckles** [comment]
#437 closes this

**Comment by tracykteal** [comment]
I think some of them are labeled 'discussion' rather than 'challenge'. It seems like both should be open by default. I'll reopen and make that change.

**Comment by rgaiacs** [comment]
@jduckles we talked about using submodules to isolate the template from the lesson. Make that change will make "fix" like #437 much harder.
