### ISSUE TITLE
Broken links in episode 12

### ISSUE THREAD

**Issue by weaverbel** [swcarpentry/instructor-training#446]
The first two links to Data Carpentry lessons in episode 12 are broken. I fixed them in my workshop website by creating absolute links but people will keep getting broken links when they import this repo until they are fixed. 

I would have edited them and done a PR but could not actually see what was wrong - everything *looks* right, but you get a 404 error when you try to open them.

The broken links are:
Faceting and Clustering in OpenRefine: http://datacarpentry.org/OpenRefine-ecology-lesson/01-working-with-openrefine.html

Basic Queries in SQL: http://datacarpentry.org/sql-ecology-lesson/01-sql-basic-queries.html

**Comment by ErinBecker** [comment]
Thanks Belinda. It's the ".html" extension bit that's messing things up. I'll get this fixed asap.
