### ISSUE TITLE
add Etherpad template

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/instructor-training#448]
When I taught with @raynamharris and @smcclatchy in March, they set up a great Etherpad organizational scheme. I've copied over the outline to a template that I'll be using for my training with Karen Word at Stanford next week. 

I'd like to add this to the Instructor notes as a template for others to use. 

Any suggestions? +1/-1?

Here's the template: http://pad.software-carpentry.org/ttt-template

**Comment by raynamharris** [comment]
This is great! I've been keeping my working template in markdown-formatted text file, but this will make implementation so much easier! Thanks!

**Comment by lexnederbragt** [comment]
Very nice! Duly added a link to http://pad.software-carpentry.org/trainers (I didn't want to add this to the pad-of-pads)

**Comment by ErinBecker** [comment]
Great, thanks @lexnederbragt! 

At the Trainer Training meeting today we made a list of things that would be good to clarify the documentation for (in terms of policies and procedures, resources, for running instructor training events). @maneesha and I will be following up to organize those suggestions, put together documentation and add to the appropriate locations. This will definitely be one of those resources (glad to hear that folks think it will be useful!), so we'll be thinking about where to add this and other resources so that they're easy for Trainers to find. Hopefully we'll have some draft documentation together before our next Business meeting and can get feedback then.

**Comment by ErinBecker** [comment]
This Etherpad template needs to be updated to match the new instructor training materials.

**Comment by ErinBecker** [comment]
Incorporated into checklist. Closing here.
