### ISSUE TITLE
no-show policy

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/instructor-training#453]
This module (https://swcarpentry.github.io/instructor-training/21-carpentries/) includes a section on no-show policy.  Is this policy anywhere on SWC or DC websites?  If so it should be linked to from here.  If not we should add it in.

**Comment by ErinBecker** [comment]
@tracykteal @jduckles Can you clarify please? Is this policy live on the website anywhere?

**Comment by ErinBecker** [comment]
@maneesha It doesn't appear to be on the websites, but it is public in its final version here: https://github.com/carpentries/policies/blob/master/instructor-no-show-policy.md
