### ISSUE TITLE
Carpentries module - Governance for SWC and DC

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/instructor-training#455]
Governance section includes governance for SWC but not DC

**Comment by ErinBecker** [comment]
Current text includes both: 

### Governance

Software Carpentry is a democracy:
its seven-member [Steering Committee]({{ site.swc_site }}/scf/ ) is elected annually
by and from its membership,
which includes every instructor who has taught in the two years leading up to the election.
The Steering Committee has final say on all strategic and financial decisions;
if you would like Software Carpentry to take a new direction,
or would like to do more than teach or develop lessons,
you are very welcome to put your name forward as a candidate.

Data Carpentry is governed by a volunteer Steering Committee and run by its Staff. 
The Steering Committee provides strategic vision and oversight of Data Carpentry.
Staff and Steering Committee members are committed to ensuring that activities are 
welcoming and inclusive, and the organization and all its events and communications 
adhere to a Code of Conduct.
