### ISSUE TITLE
Carpentries module - debriefing section inaccurate

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/instructor-training#456]
> Since January 2015 we have run bi-weekly debriefing sessions for instructors who have recently taught workshops. In these, instructors discuss what they actually did, how it worked, how the lessons they actually delivered differed from our templates, what problems arose, and how they were addressed. Summaries are posted on our blog shortly after each meeting, and eventually added to our operations guide.

We now call these discussion sessions, not debriefing. They open to people who are about to teach to ask questions, for people who have recently taught to debrief as above, and for new trainees to ask questions as part of the checkout process.

**Comment by raynamharris** [comment]
Can we just delete this paragraph? It seems a little out of the place anyways, in this section under workshop operations.

**Comment by ChristinaLK** [comment]
Yes, there's now a slight reference to the discussion sessions under joining the community, which seems like a more appropriate place.
