### ISSUE TITLE
Practice with infrastructure: need to include DC and SWC

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/instructor-training#459]
In the Carpentries module Setting up section -
We have a Practice with SWC infrastructure exercise.  This should be changed to practice with SWC or DC and include links to both program's templates.

**Comment by amoskane** [comment]
Hi, I made a commit for this fix but when I try to push my branch I get "remote: Permission to swcarpentry/instructor-training.git denied to amoskane."

**Comment by mkuzak** [comment]
@amoskane thank you for your eagerness to contribute to the lessons. If you would like your changes to be included, please fork the repository first, and then create a pull request with your changes. The lesson maintainers will review your contribution and merge it if they agree it fits. Please have a look at our [contribution guidelines](https://github.com/swcarpentry/instructor-training/blob/gh-pages/CONTRIBUTING.md) before considering the pull request.
