### ISSUE TITLE
Share Rayna's haiku in motivation section (and note who Rayna is)

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/instructor-training#463]
I'm really interested to see the haiku Rayna uses to teach shell commands.

Also most people are not going to know who Rayna is.  Maybe say 
 

> Or,  use Rayna’s personal story (another instructor and trainer), which goes like `this....

**Comment by raynamharris** [comment]
The UNIX grep hakaui example is found in the "Finding Things" Episode. It refer to it a lot. http://swcarpentry.github.io/shell-novice/07-find/

**Comment by raynamharris** [comment]
Okay, I created pull request https://github.com/swcarpentry/instructor-training/commit/f6447c10bb3f624a44722e3cba7a3e3018e2c4b1 to attempt to clarify some of these points.

**Comment by ErinBecker** [comment]
Thanks @raynamharris! Merged.
