### ISSUE TITLE
Brainstorming Demotivational Experiences

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/instructor-training#464]
Here we ask people to

> Think  back to a time when you demotivated a student (or when you were demotivated as a student)....

Can we flip this:

> Think  back to a time when  you were demotivated as a student (or when you demotivated a student)....

It may feel intimidating (and demotivating!) to have to reveal a time when you were the demotivator.   Learners may feel more comfortable thinking first to when they were demotivated and then give further thought to when they were the demotivator.

**Comment by lexnederbragt** [comment]
+1 from me, good idea.
