### ISSUE TITLE
Live coding exercise not authentic

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/instructor-training#471]
From trainees at Stanford: 
- not having a shared screen makes it hard for "learners" to follow-along
- "learner" isn't working along with you during live coding
- need to be reminded to take sticky notes with them to break-out room

**Comment by raynamharris** [comment]
Is there an alternative? 

I have started to preface this exercise by explicitly stating the top two bullet points. I don't have the data to show that this works, but I think it helps if you tell people up front that this exercise isn't authentic but it is good enough.

**Comment by ChristinaLK** [comment]
I don't think of this exercise as authentic, but as practice -- like a rehearsal before you perform.  
Maybe clarify in the exercise text?

**Comment by jduckles** [comment]
I agree that I have prefaced this as an example of trying to teach and type at the same time, not a completely authentic workshop experience.

**Comment by jmgreenb** [comment]
I agree with ChristinaLK and jduckles.  From how I understood and experienced it, it was more for me to evaluate my ability to go through a piece of the lesson I chose and to work on my presentation and fluidity, not about whether they can actually follow me from their own computer.
