### ISSUE TITLE
Explicitly addressing color blindness as part of accessibilty

### ISSUE THREAD

**Issue by ashleyjester** [swcarpentry/instructor-training#474]
In the "Motivation and Demotivation" section, there is some discussion about making sure the instruction materials and space are accessible.  Given that about 8% of the male population experiences some degree of color impairment, it seems worthwhile to mention directly in this section that color choice for the notification flags and presentation materials should be done with this in mind.

ColorOracle (http://colororacle.org/) is a good free tool for checking websites.  ColorBrewer (http://colorbrewer2.org) has a listing of color-blind compatible color schema.

<img width="1288" alt="screen shot 2017-05-22 at 8 54 47 am" src="https://cloud.githubusercontent.com/assets/19556329/26317485/795d5cba-3ecc-11e7-8db5-b4dcb680ed22.png">

**Comment by ErinBecker** [comment]
@ashleyjester - Thanks for this suggestion. It has also been raised at subsequent instructor training workshops. I think this is best incorporated in the discussion about sticky notes in the live coding and carpentry practices episodes. The PR referenced above makes this change to the live coding episode. Adding to the lesson cleanup checklist for the carpentry practices episode and closing here.
