### ISSUE TITLE
Explicit Trainer agreement

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/instructor-training#477]
New issue started from https://github.com/swcarpentry/instructor-training/issues/349. 

See [the agreement draft here](https://docs.google.com/document/d/12E4Zw7q61plmSHshK7ZEl1YsQNhJ_4kYVfyynElbTyI/edit). 

This is being considered for vote by the Trainers at our meetings today. 

Votes so far: +10, -0

**Comment by gvwilson** [comment]
👍

**Comment by ErinBecker** [comment]
Trainer agreement has been approved unanimously by the Trainer group. 

Final text is [here](https://github.com/carpentries/policies/blob/master/trainer-agreement.md).
