### ISSUE TITLE
"It ain't what you know" quote misattributed to Mark Twain

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/instructor-training#488]
See:

http://www.mcall.com/opinion/white/mc-bw-bloopers-20160627-column.html
https://newrepublic.com/minutes/126677/it-aint-dont-know-gets-trouble-must-big-short-opens-fake-mark-twain-quote
https://www.forbes.com/2009/08/12/nigel-rees-misquotes-opinions-rees.html
https://scatter.wordpress.com/2016/01/16/the-big-short-and-the-most-ironic-quote-misattribution-ever/

**Comment by ErinBecker** [comment]
This quote was removed in the new version of the materials.
