### ISSUE TITLE
Author "Fisk" should be "Fink" because the taxonomy is from L. Dee Fink.

### ISSUE THREAD

**Issue by dmgatti** [swcarpentry/instructor-training#491]
This lesson is currently being prepared for publication and is under development at https://github.com/ErinBecker/instructor-training-reorg/. Please submit any issues or PRs to that repo (not here).

In the header of the table containing Bloom's Taxonomy, column 3 says (Fisk) and it should say (Fink). See https://www.amazon.com/Creating-Significant-Learning-Experiences-Integrated/dp/1118124251 .

**Comment by lexnederbragt** [comment]
Fixed in the 'work-in-progress' material, see https://erinbecker.github.io/instructor-training-reorg/14-learning-objectives/.

Thanks!
