### ISSUE TITLE
Change how we communicate lesson contribution expectations

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/instructor-training#502]
After 2017-09-21 community call about lesson maintenance, a question came up about how trainees can do their lesson contributions.  It was suggested we change the wording to make it clear that*any* contribution is equally valid -- submit a pull request,  submit an issue, contribution to PR, participating in conversation on any of these things, etc.

**Comment by ChristinaLK** [comment]
duplicated by @tracykteal in #501
