### ISSUE TITLE
Have trainees submit solutions to exercises as well

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#52]
Trainees should submit solutions to exercises (particularly advanced ones).

**Comment by jdblischak** [comment]
+1

**Comment by ChristinaLK** [comment]
+1000000

If we move to an "exercise bank" format for the lessons, it would be great to have an accompanying solution bank, especially so that it's clear what each exercise is trying to accomplish (per #54)

**Comment by gvwilson** [comment]
Next question: format.  I think it make sense to keep each exercise in a 
single blockquote, and use an internal level-3 heading titled "Solution" 
to separate the question from the answer, so that we can easily hack up 
a bit of JS to hide/show the solution.  Separate blockquotes or 
HTML-style div's seem fragile to me. Thoughts?

**Comment by ChristinaLK** [comment]
This is starting to fall outside the scope of instructor-training - I think this should be discussed on discuss and/or maintainers and/or with people who have built up a lot of the lesson formatting infrastructure.  Hopefully someone (not me) volunteers to take charge to then keep the ball rolling...

**Comment by gvwilson** [comment]
Agreed.

**Comment by jdblischak** [comment]
Where is this new discussion on the format taking place? I currently have 6 PRs to r-novice-inflammation, and I'm not really sure how to advise them on formatting. Not one of them added anything to the Instructor's' Guide, even though that is specified in the current [layout instructions][layout]. What directions were they given? Are we still adding solutions to challenges to the Instructor's Guide? I'd rather not have to format all these myself post-merging, but I also don't have any documentation to give them for how to proceed.

[layout]: https://github.com/swcarpentry/lesson-example/blob/gh-pages/LAYOUT.md#instructors-guide

**Comment by gvwilson** [comment]
There isn't a new discussion on format yet beyond this thread - we're 
not going to make any changes until the current rush of PRs settle 
down.  For the next couple of months at least, they're to use the 
existing format without alterations.

**Comment by ChristinaLK** [comment]
@jdblischak I've never used that format for `instructors.md` for the shell lesson. :P Maybe we need a quick email around maintainers to ask how people are planning to deal w/ the flood of PRs?

**Comment by jdblischak** [comment]
Exactly the problem. I just checked all the novice lessons, and only python-novice-inflammation and r-novice-inflammation contain challenge solutions in the Instructor's Guide. I wish the maintainers would have been given advanced noticed so we could have had this conversation prior to the flood of new PRs. It is my understanding that the new trainees need their PRs merged to become instructors, so I don't think we should make them wait for the maintainers to decide on how to update the lesson template documentation.

**Comment by ChristinaLK** [comment]
well, we didn't have an advance-notice discussion, but I think we could still do it now - waiting one week to have their PR reviewed probably won't hurt anyone.

**Comment by karinlag** [comment]
+1000 to having people submit exercises with solution, even better if they explicitly state novice, intermediate, advanced on them.

**Comment by gvwilson** [comment]
Closed by #134.
