### ISSUE TITLE
Have trainees explain the purpose/takeaways of the exercises they submit

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#54]
Trainees shouldn't just supply an exercise: they should explain what it's teaching.

**Comment by apawlik** [comment]
Do you mean the exercises they submit post-training (as a part of the checkout procedure)? Or the exercises developed during Instructor Training session? If the former, I suggest to add that to the document with the Instructor Checkout Procedure.

**Comment by gvwilson** [comment]
Closed by #134.
