### ISSUE TITLE
Tell trainees to give exercises a scientific theme

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#55]
Exercises about bank balances or children's birthday parties aren't as appealing to our audience as ones dressed up as science.

**Comment by apawlik** [comment]
Based on the experiences from past Instructor Training events and discussions with @tracykteal and @gvwilson , we could try theming the exercises as follows:

Exercise 1 - Formative assessment - MCQ on a topic from the 1st year undergrad in your discipline
Exercise 2 - Recorded teaching: introduce yourself and coolest thing in your research/work
Exercise 3 - Concept map on the above coolest thing (alternative: the MCQ topic)
Exercise 4 - Faded example on the coolest thing or MCQ topic (whichever is more suitable for the faded example)
Exercise 5 - Learning objectives for the coolest thing / topic from the MCQ 
Exercise 6 - Recorded teaching based on the developed concept map and learning objectives

**Comment by ChristinaLK** [comment]
Greg, do you mean hear that we should tell trainees to use science-themed exercises when they write / contribute to lessons?  Or as @apawlik as written above, that the exercises we use in the instructor training be science-themed?

**Comment by gvwilson** [comment]
The former: trainees contributing to lessons should be asked to write 
science-y stuff.

**Comment by karinlag** [comment]
On 12/01/16 15:37, Greg Wilson wrote:
> The former: trainees contributing to lessons should be asked to write
> science-y stuff.
>

...so this would be when trainees contribute to the teacher training 
material, yes?

Karin

**Comment by gvwilson** [comment]
Sorry for the confusion: people who are being trained _as instructors_, 
not as instructor trainers, are expected to write science-y exercises 
for our lessons as part of their checkout exercise.  We don't currently 
require people who are becoming instructor trainers to contribute 
anything specific to the instructor training material.

**Comment by gvwilson** [comment]
Closed by #134.
