### ISSUE TITLE
Phonics vs. whole word reading

### ISSUE THREAD

**Issue by arokem** [swcarpentry/instructor-training#60]
Might not be a great example. According to my colleague, who is a professor in Speech and Hearing, and an expert on reading, there's a scientific consensus that whole-word reading was a bad idea and phonics is the way to go (references to follow...). Therefore, the sentence "Both approaches are consistent with what we know about how children learn" might not be accurate, and the inferences that follow might not hold.

**Comment by gvwilson** [comment]
A PR with better wording would be welcome :-)

**Comment by arokem** [comment]
How's that?
