### ISSUE TITLE
Add discussion of data sets, Windows installer, and update-copyright

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#62]
*   https://pypi.python.org/pypi/update-copyright/ should be discussed
*   The Windows installer should be discussed
*   Our data sets should be discussed

**Comment by apawlik** [comment]
As I understand that would fall under new lessons/modules which we deliver on Day2 (in case of 2-day training) when discussing the operations, setting up workshop websites etc. 

With Windows installer - how much detail you want? I would be for just signposting for trainers which bits of the infrastructure need to be covered and put relevant links in. The reason for this is that whilst our infrastructure changes now much more slowly than it used to, it will still be moving and every time we need to remember to propagate updates (like here). Thoughts?
