### ISSUE TITLE
Different exercise for Faded Examples

### ISSUE THREAD

**Issue by apawlik** [swcarpentry/instructor-training#68]
Coming up with a faded example during the session is extremely difficult for the trainee instructors. I suggest a different exercises: give them 2 examples of "broken" faded examples to fix. That is, give them 2 examples with description what problem they are teaching student to solve and ask the trainee instructors to fix/improve these examples. The examples should be "broken" in a way that the faded/taken out bits will be completely random, the teaching would not be effective. This would also allow the trainee instructors to better grasp the idea of what intrinsic, germane and extraneous load. I need some time to think about this but will try to submit something soon.

**Comment by apawlik** [comment]
Another/additional idea - ask the students to identify which *could* be intrinsic, germane and extraneous bit in the faded examples presented. For example, if it's a coding faded example (currently in the materials):
-  the intrinsic knowledge is knowledge of programming *concepts*, knowledge how to type, how to use some kind of text editor; 
- germane is learning how to loop through a collection;
- extraneous (if we show them a "broken" example) could be something like "import numpy" because the example would be looping through some numpy structure (so kind of "overcomplication") - this needs better grounding in the theory, but just noting the idea here.

**Comment by ChristinaLK** [comment]
My two cents: I didn't have students create a faded example - just walked them through it.  

I like the idea of having participants identify types of knowledge in either the faded example, or some other teaching/lesson example.

**Comment by apawlik** [comment]
Tried out this at Melbourne IT January 2016

- Talk about battling theories and then 3 different kinds of load (short but clear)
- Then thrown into the Etherpad the example we have in materials
- put them in groups (we were in a collab space so naturally they split into groups at the tables of about 4-5)
- ask them to discuss and identify in groups what different loads occur 


This worked pretty well I think, they seemed to be very engaged and liked it. Though there were lots of questions.
- I put the definitions of 3 loads into Etherpad so that they had them in front of them
- Trainer needs to define who the audience is for these examples (because for example, you could use it for someone who programs pretty well in C and wants to learn some specific Python syntax and the Python heavy weightlifting that doesn't exisist in C)
- Would be good to have some examples ("Intrinsic load: ability to read and write; understanding what variable is", "Germane load:....", "Extraneous load...."
- I had 3 people who don't program at all - I made sure that they were in separate groups and said to the groups to work with that person as a learner to help identify different loads (are we able to/does it make sense to have an example, or backup example which is generic? doesn't require programming knowledge).

**Comment by gvwilson** [comment]
@apawlik can you please PR this?

**Comment by apawlik** [comment]
An attempt https://github.com/swcarpentry/instructor-training/pull/153

One thing we need to note in the materials or Trainer's Guide is that Faded examples work well in the type of knowledge which is algorithm based. I think that faded examples used for example in history may actually only check factual knowledge, rather than teach problem-solving.

In general, I think we need someone who understands congnitive load stuff well to improve the practical side of this lesson At most Instructor Training sessions I ran, people were pretty confused with this and struggled to relate this to teaching (SWC/DC workshops and teaching in general).

**Comment by lexnederbragt** [comment]
I wasn't aware of faded examples until I saw the disussion of them in the instructor training material a couple of weeks ago. The lessons I know well (shell, git unix) don't (or didn't) have faded examples. Is this kind of exercise 'the new thing' now, and should we (or have we already) add(ed) them to the core lessons? Pardon my ignorance, I may have missed a discussion on this...

**Comment by gvwilson** [comment]
We don't have any in the current lessons, but we'd like to encourage 
people to start submitting them.

**Comment by apawlik** [comment]
Yes, definitely it would be great to have a selection of faded examples in our materials. Also because we could refer back to the SWC/DC materials showing that we really use what we preach for. More examples would also be very helpful for the Trainees to understand what faded examples are (teaching **strategy** to solving problems) and provide an opportunity to think about different kinds of cognitive load that occur. 

Cognitive load theory  is one of the most challenging bits of the Instructor Training at the moment and I feel it is because we don't have good enough exercises. More examples in our lessons could help with developing exercises for the IT.

**Comment by lexnederbragt** [comment]
Would an exercise like 'list all the things a learner needs to know in order to write a for loop in bash (or python)' help?. Followed by part 2: 'what would be added to this list if the exercise were to be done in a Jupyter Notebook?'. Followed by the explanation that, for example, this is one of the reasons we don't use the notebook for teaching the unix shell?

**Comment by gvwilson** [comment]
An example from today's instructor training is a few lines of R to draw a simple plot, and then each fade after that (a) changes something about the plot being drawn (e.g., show max instead of ave, or scale, etc.) and (b) has more blanks.
