### ISSUE TITLE
feedback on video training

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#72]
1.  Allow more time for trainers to review feedback after first exercise
2.  Give more direction on what kinds of feedback to provide
3.  Provide more direction on how to do the exercise (reiterate a couple of times then ask someone what they think they're supposed to do)

**Comment by apawlik** [comment]
Ad 2. (as per Greg's suggestion) Grid: Performance / Contents +/ - works well.

I also tell them to time themselves on feedback. So for example "5 min feedback for each video; please time yourselves on that too". It helps.

**Comment by gvwilson** [comment]
Closed by #140.
