### ISSUE TITLE
Rewrite schedule in instructors.md

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#75]
Replace detailed schedule in instructors.md with a more accurate one.

**Comment by apawlik** [comment]
I should be able to make some amendments after next week. I am able to more or less stick to the one I submitted in https://github.com/swcarpentry/instructor-training/pull/50 Though day 2 actually needs some more work (also in terms of material and contents).

**Comment by gvwilson** [comment]
Duplicates #38.
