### ISSUE TITLE
Contents on "Materials and how to contribute" (Day2)

### ISSUE THREAD

**Issue by apawlik** [swcarpentry/instructor-training#76]
That should either go to the contents of the actual training or in the trainer's notes. It's actually easy to get messy with "Our materials, how to contribute" and so on. Some of my suggestions (used at the Australia and NZ IT in January 2016):

1. Start off with talking about collaborative material development in more general terms (proliferation of materials, why it happens, everyone has their version of slides, improvements never contributed back, analogy with OSS).
2. Show where our materials are (using Lesson sections in DC/SWC websites). Show the website and how it connects with the source (GH).
3. Show briefly [this paper](http://alexeyza.com/pdf/cscw15.pdf).
4. Show a discussion thread on one of the PRs which contains a change in materials. This demonstrates well why GH is so useful (vs Wikipedia or comments in Google Doc etc). It also shows the openness of the community.

I always also say that we understand the problem of high-barrier entry with GH and ask if people know of any useful tools.

**Comment by ChristinaLK** [comment]
addressed in above PR
