### ISSUE TITLE
Create a bank of anecdotes

### ISSUE THREAD

**Issue by apawlik** [swcarpentry/instructor-training#77]
I am terrible remembering them. Also probably don't read enough/the right stuff. Essentially, my training sessions are quite dry and at times probably boring.
Having seen Greg teach with all the stories he adds here and there I know that it makes a big difference. So, please share the anecdotes with killjoys like myself :-)

**Comment by gvwilson** [comment]
I'd welcome additions to the instructors' guide, but I think anecdotes only work if they're people's own.

**Comment by apawlik** [comment]
Yeah, but what if you have no anecdotes of your own?! I need to learn them by heart from a source. I don't retain anything I read (and I anyways don't have time to read anything else than my emails).

**Comment by gvwilson** [comment]
Um... you have *no* stories to share from your time with SSI?  This is 
my shocked unbelieving face...

**Comment by apawlik** [comment]
Oh, I have many but they aren't along the lines of "Rostropovich's broken toe". Actually it feels like I have none. I am brain-dead for anecdotes. I remember the best stories and jokes about 2 hours after the moment you need them. Looks like my secret dream of becoming a talk-show host will never come true...
