### ISSUE TITLE
Feedback from Lausanne

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#83]
1. More time for video exercises. Also provide them guidance about how much time they should spend on each feedback. So for example: each video 2 minutes and each feedback about 3 min. I think they were also running out of time because we didn't tell them how long to give feedback on one video. Giving them just the grid for feedback is not enough to structure it.

2. Theming the exercises on Day 1 (so build MCQ, concept map and then Learning Objectives) was something that people really liked.

3. More time for the video on Day 2 when they record themselves live coding. Also give them better guidance for preparations that we want them to pick something from the middle of the materials so that they actually spend most time doing live coding than introducing the topic. This should actually be really well demonstrated during the demo (i.e. how to teach stuff taken out of context and make assumptions that for example people already opened their terminals).

4. During the live coding demo, Tracy purposely made some common mistakes - this worked well when collecting feedback (we did one up one down).

5. A very high level comment: when talking about the concepts/theory the trainer needs to make very clear and probably a good few references back to how it ties in with SWC/DC. Sure, yeah, this is supposed to be generic part of the training. However, people come in for SWC/DC and they want to know "Why are you teaching us about cognitive overload? Is this used in SWC/DC". This basically boils down to the trainer being very well read in the pedagogical topics we cover and also be an experiences instructor.

6. People would like to get some kind of a list of the main concepts. Personally I (Aleksandra) think that we could have in the repo a simple print out sheet which only has a list of these key concepts ("Summative assessment. Formative assessment. Mental model. Concept map. COngnitive overload. …….) with spaces left between them and print them and hand them out. People can take notes on them. Taking notes in Etherpad is not great - it becomes messy. People are taking notes in their notepads anyway but they need a highlight/signpost - we say many words during the training but they sometimes are not sure which were the key ones.

7. The part on "Materials and how to contribute" needs better structure. Open discussion is rubbish. EIther we decide we focus on the "meta" level - talk about what we need in terms of materials, the flow in the community (maintainers, contributors, small changes vs large overhauls etc). or we discuss the mechanics (PRs). Personally I think the latter, the risk is that people in the IT who know Git well get bored. We should rather think about having a support group for people who want to learn Git too be able to do PRs to materials and then explain trainees how they can get into contributing to materials.
I would also cover more about how friendly the community is - showing examples of good discussions under PRs (possibly controversial PRs). I also showed how the thread on Discuss list about "Leaving novices behind" turned into blog post.

What we need to emphasise and cover better in our day2 of the IT is the community of practice that we have, how good it is, what it brings, (also explain what "community of practice is"), how we facilitate it. This is our amazing asset and people coming to IT need to know this because THIS is what will pull them in.

**Comment by ChristinaLK** [comment]
all suggestions split into sub-issues or addressed in PRs

**Comment by gvwilson** [comment]
Thanks much.
