### ISSUE TITLE
Don't use the word "pipeline" for instructor progression

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#91]
People aren't crude oil - we should find some other metaphor for instructor progression.

**Comment by davidedelvento** [comment]
Where is pipeline mentioned?

**Comment by embray** [comment]
Huh--this is a new critique to me.  But :+1: 
Same for CS pipeline, STEM pipeline, etc...

**Comment by embray** [comment]
(Part of me wants to use some kind of role playing game metaphor like "advancing on the skill tree" but that doesn't really work either....)

**Comment by karinlag** [comment]
How about something with the word upskilling?
