### ISSUE TITLE
SoL 2: How Do Students Learn and Retain New Information?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#93]
Discussion thread for this SoL.

**Comment by lexnederbragt** [comment]
**Treated**

* "assign students tasks that require explanation or that require students to meaningfully organize material"

—> Treated in `05-expertise`: having learners build concept maps during the workshop

* "Practice is essential to learning new facts, but not all practice is equivalent"

—> Practice is part of the instructor training itself, and in `07-design`, in the part on "Reverse Instructional Design", _designing practice work_ is mentioned as part of lesson design. However, there does not seem to be much focus on the importance of having the learners do exercises during the workshop. This could be added as another bullet point under "Other Practices" in `08-practices`.

* "Teachers can explain to students that trying to remember something makes memory more long-lasting than other forms of studying. Teachers can use low- or no-stakes quizzes in class to do this, and students can use self-tests"

—> Treated in `03-models` with formative assessment, in particular multiple choice questions

**Not treated**

* "Teachers can help students learn to impose meaning on hard-to-remember content. Stories and mnemonics are particularly effective"

—> It would be useful to stress the importance of figures/diagrams (many lessons have them) and even better, making drawings on the white/blackboard during the teaching as a tool for this, and to help build mental models

* "Teachers can space practice over time, with content being reviewed across weeks or months, to help students remember that content over the long-term” 

—> We don’t have months or weeks 

* "Teachers can interleave (i.e., alternate) practice of different types of content"

—> The lesson material provides for this, and it could be mentioned in the suggested new bullet point under "Other Practices" in `08-practices` (see above)
