### ISSUE TITLE
HLW 2: How Does the Way Students Organize Knowledge Affect Their Learning

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#98]

**Comment by raynamharris** [comment]
One important way that experts and novices differ is in how they organize information learned. Novices often fail to see the relationship between things that are actually connected (like events happening at the same time in different parts of the world, or how different organ systems in the body interact, or how Unix command can be linked with pipes or scripts). However, experts often aware of the many connections between facts, concepts, and skills they know. 

![img_0585](https://cloud.githubusercontent.com/assets/7544197/14390704/092ae952-fd7e-11e5-9c14-a9350122db1a.JPG)

This figure provides an illustration of how novices (A, B) and experts (C, D) organize information. The expert’s knowledge structure is characterized by a dense connections between nodes while the novice organized information is discrete units or a chain of associations

If we provide students with an organization scheme for making connections, they can begin to form more meaning associations between related concepts. For instance, “chuncking” (grouping bits of knowledge) is one process by which learners create a highly organized knowledge structure, which allows them to develop exceptional memory ability and to recall a great deal of information. Another option is to present (or have the students make) concept makes that explicitly link related skills, theories, facts, etc. When observing students concept maps, look for and diagnose inappropriate connections that could be impeding the student’s performance or understanding.


Why this matters, IMO. Often times we give students exam questions or challenge problems that assume students have made a connection between two concepts that we have yet to explicitly lay out. This can be a major source of frustration for learners, so it is important to take the time to help students progress beyond the novice way of organizing knowledge into discrete clusters and to make stronger connections between related clusters.

**Comment by raynamharris** [comment]
# Places in the curriculum where these concepts are taught:

## 03-models.md

### Cognitive Development and Mental Models
One way to think about the difference between a novice and a "competent practitioner" is the existence of this big picture mental model

### Getting to Strong Mental Models
There are many "positive" strategies towards building mental models. Analogies, stories, role-play, diagrams...all can be a way to represent a structure that can be used as a model. Clearing up learners' misconceptions is therefore as important as presenting them with correct information.

## 05-expertise.md

###  Connectivity
The key difference between experts and people who are "merely competent" is that experts have many more connections, i.e., their mental models are much more densely connected.

### Concept Maps
Our tool of choice to represent an expert's knowledge graph is the concept map. A concept map is simply a picture of someone's mental model of a domain: facts are bubbles, and connections are labelled arcs.
