### ISSUE TITLE
SoL 5: What Motivates Students to Learn?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/instructor-training#99]

**Comment by weaverbel** [comment]
The SoL point about student's ability to improve is covered by the fixed mindset/growth mindset material in our material. 

The reward section is pretty much equal to the establishing value and relevance bit of our training as it talks up learning goals above performance goals as a way of deepening learning.

The "monitor their own learning" point is not so much addressed in motivation but more in the earlier workshop material such as multiple choice questions or challenges within the workshop to test whether students have grasped what has been taught. So it is dealt with.

Equally, the final point about a supportive environment fostering learning has been well and truly emphasised.

Therefore, I don't think the SoL principles have a huge amount to add that has not been already covered in the material - it may just be that it was said in a slightly different way. 

But the SoL is really saying the same things as *HLW* - establish the value of what they are about to learn and its relevance to their life and work, provide a nurturing learning environment, and give them tasks where they can test their own competency.
